### PR TITLE
Use 'well-formed' (with hyphen) consistently.

### LINKED ISSUE #1618: "well formed" vs. "well-formed"
Those seem to be used more or less interchangeably in the standard.  Are they the same? If so, shouldn't they be written the same way?

"Well formed" --> 100+ uses
"Well-formed" --> 22 uses.

I can provide a list upon request.

### PR DESCRIPTION
**Pull request by jensmaurer**
Fixes #1618.

### CODE REVIEW

**Comment by jensmaurer** [comment]
I've also updated the "Specification Style Guidelines" wiki page.

**Comment by Eelis** [comment]
Typo in commit name ("consistenly")

**Comment by jensmaurer** [comment]
Rebased and fixed typo in commit message.

**Comment by jensmaurer** [comment]
Rebased.

**Pull request merged**
