### PR TITLE
[strings, algorithms, diff] Replace 'routine' with 'function'.

### PR DESCRIPTION
**Pull request by Eelis**
These are the only occurrences.

### CODE REVIEW

**Comment by jensmaurer** [comment]
Looks good to me.

**Comment by tkoeppe** [comment]
@jensmaurer: Are you sure that "function" doesn't subtly introduce a more constrained notion than "routine"? I'd be happy to merge if you are confident that this is correct.

**Comment by Eelis** [comment]
For fun, I searched for occurrences of "routine" in the C99 standard. Of the five I found, three appear as synonym for "function", one occurs in "objects referred to by interrupt service routines activated by the signal function" (which I guess refers to callback functions), and the fifth and most interesting one is:

> Aprincipal use of the sizeof operator is in communication with routines such as storage allocators and I/O systems.

Sounds old-timey to me, haven't heard of an I/O system referred to as a "routine" recently. :)

**Comment by jensmaurer** [comment]
@tkoeppe: "routine" is an undefined concept in C++. I've reviewed the patch again, and in all cases, we're directly talking about "functions" as C++ understands them. Mentioning a "routine" is just a colloquialism that crept in.

**Pull request merged**
