### PR TITLE
More consistent formatting of complexity requirements and others.

### PR DESCRIPTION
**Pull request by cassioneri**
Many changes to formatting of complexity clauses, especially, when math and code are mixed.

### CODE REVIEW

**Comment by tkoeppe** [comment]
Could you please rebase, and/or advise on whether this PR is still needed?

**Comment by tkoeppe** [comment]
@cassioneri: Ping - could you please review your PR?

**Comment by jwakely** [comment]
I've done the rebase and I think **only** 3130157 is still needed. See the result at https://github.com/jwakely/draft/commit/44b21acb0c4e5a73fa0af7ad87a427528bd827a1

**Comment by tkoeppe** [comment]
@jwakely: `diffpdf`, `ksnapshot` and then copy-paste into GitHub :-)

**Comment by jwakely** [comment]
Most of the changes look good, but do we really want to change:

Exactly `max((last - first) - 1, 0)` applications

to:

Exactly max(`last - first` - 1, 0) applications

?

Similarly, `2*min(...)` might be clearer than 2min(`...`)

**Comment by tkoeppe** [comment]
@jwakely: The last one should be set as maths, `$2 \min( ... )$. Then it looks good I think. If you have it all as code, then keep the operator: `\tcode{2 * min(last - first, 0)`. But I think that's inferior, because it needlessly refers to a function `min` now rather than to the mathematical concept.

**Comment by jwakely** [comment]
Yes maybe we just need a space between the "2" and "min"

**Comment by tkoeppe** [comment]
The math mode spacing should be appropriate out of the box. Math mode is whitespace insensitive by the way, so `$2\min$` and `$2 \min$` render the same.

**Comment by tkoeppe** [comment]
@cassioneri: Hi - are you still working on this? It looks like a worthwhile cleanup!

**Comment by cassioneri** [comment]
Hi Thomas

Unfortunately, I'm not. Since I got a new job I went away from the C++
party. I miss that very much.

I'm sorry I can't help now but I hope to come back one day.

Best regards,
Cassio.

**Comment by tkoeppe** [comment]
OK, thanks. That's a shame!

@zygoloid: Close this PR?

**Comment by tkoeppe** [comment]
@zygoloid: I've downloaded the changes in this PR, please feel free to close it.

**Comment by jwakely** [comment]
Closing, the remaining pieces will be dealt with separately.

**Pull request closed without merging**
