### PR TITLE
[range.chunk] Add the class template description for `chunk_view`

### PR DESCRIPTION
**Pull request by hewillk**
Note that I also removed the "`<V>`" part in "Class template `chunk_view<V>​::​iterator` for forward ranges" to be consistent with other sections.

### CODE REVIEW

**Comment by hewillk** [comment]
> Note that I also removed the "`<V>`" part in "Class template `chunk_view<V>​::​iterator` for forward ranges" to be consistent with other sections.

This may not be an appropriate choice since this "`<V>`" is needed for class partial specialization.

**Comment by JohelEGP** [comment]
The "for forward ranges" part is clarifying enough to me.

**Comment by tkoeppe** [comment]
Please rebase?

**Comment by tkoeppe** [comment]
@hewillk Ping ^^^

**Comment by hewillk** [comment]
Is this acceptable?

**Review by jensmaurer — APPROVED** [review]

**Comment by jensmaurer** [comment]
The change itself looks good; the two commits should be squashed and force-pushed, and the commit description should be fixed.

Something like "[range.chunk] Fix subclause headings" might work.

**Pull request merged**
