### PR TITLE
[version.syn] Add digit separators between year and month

### LINKED ISSUE #5109: [version.syn] Use a digit separator to split the year and the month
A naive attempt doesn't work in LaTeX:

Even then, I find the dates look better:
Before:
a
After:
b

### PR DESCRIPTION
**Pull request by jensmaurer**
Fixes #5109

digsep

### CODE REVIEW

**Comment by timsong-cpp** [comment]
The exact spelling of the macro is observable to stringization and token concatenation though?

**Comment by jensmaurer** [comment]
Do you have an example? This one isn't one:

```
#include <iostream>

#define date 2019'07L

#define S(x) #x

int main()
{
  std::cout << S(date) << std::endl;
}
```
outputs `date`.

**Comment by JohelEGP** [comment]
https://godbolt.org/z/Wq64xrand
```C++
#define date 2019'07L
#define cat(x, y) x ## y
#define S(y) cat(x, y)
const char s[] = S(date);
```
```
<source>:3:18: error: pasting &quot;x&quot; and &quot;2019'07L&quot; does not give a valid preprocessing token
    3 | #define S(y) cat(x, y)
      |                  ^
<source>:2:19: note: in definition of macro 'cat'
    2 | #define cat(x, y) x ## y
      |                   ^
<source>:4:18: note: in expansion of macro 'S'
    4 | const char s[] = S(date);
      |                  ^
<source>:3:18: error: 'x' was not declared in this scope
    3 | #define S(y) cat(x, y)
      |                  ^
<source>:2:19: note: in definition of macro 'cat'
    2 | #define cat(x, y) x ## y
      |                   ^
<source>:4:18: note: in expansion of macro 'S'
    4 | const char s[] = S(date);
      |                  ^
```
```
<source>:4:18: error: pasting formed 'x2019'07L', an invalid preprocessing token
const char s[] = S(date);
                 ^
<source>:3:14: note: expanded from macro 'S'
#define S(y) cat(x, y)
             ^
<source>:2:21: note: expanded from macro 'cat'
#define cat(x, y) x ## y
                    ^
<source>:4:18: error: use of undeclared identifier 'x'
<source>:3:14: note: expanded from macro 'S'
#define S(y) cat(x, y)
             ^
<source>:2:19: note: expanded from macro 'cat'
#define cat(x, y) x ## y
                  ^
<source>:3:18: note: expanded from macro 'x'
#define S(y) cat(x, y)
                 ^
<source>:4:20: error: expected ';' after top level declarator
const char s[] = S(date);
                   ^
<source>:1:14: note: expanded from macro 'date'
#define date 2019'07L
             ^
3 errors generated.
```
```
example.cpp
<source>(4): error C2001: newline in constant
<source>(4): error C2065: 'x2019': undeclared identifier
<source>(4): error C2143: syntax error: missing ';' before 'constant'
<source>(4): error C2059: syntax error: 'constant'
```

**Comment by jensmaurer** [comment]
Ok. But without the digit separator, we get:

```
#define date 201907L
#define cat(x, y) x ## y
#define S(y) cat(x, y)

const char s[] = S(date);
```
which yields
```
x.cc:6:18: error: ‘x201907L’ was not declared in this scope
    6 | #define S(y) cat(x, y)
```
i.e. we get a valid _identifier_.

**Comment by jensmaurer** [comment]
@jwakely , do you feel we should file a library issue to make the presence or absence of digit separators in feature-test macros unspecified, thus making the concatenation magic shown in this issue not portable?

**Comment by jwakely** [comment]
I don't see any advantage to allowing them. Six digits, where the first four are a recent year, doesn't seem too hard to read without separators.

I want going to comment here if everybody else liked the idea, but I don't actually like the results with the separators.

**Comment by jensmaurer** [comment]
So, this is not editorial (because adding the digit separator breaks preprocessor token concatenation). The absence of digit separators is not a defect (thus an LWG issue is not the right thing).
This leaves for anyone who cares deeply to write a paper.

**Pull request closed without merging**
