### PR TITLE
Add coroutine to headers

### PR DESCRIPTION
**Pull request by leni536**

### CODE REVIEW

**Comment by tkoeppe** [comment]
Wait, why do we have this file?

And why is "5" a header?

**Comment by leni536** [comment]
Umm, disregard this PR, I thought this file had anything to do with the header index generation.

**Comment by tkoeppe** [comment]
I mean, I would still like to know why we have that file...

**Comment by CaseyCarter** [comment]
> I mean, I would still like to know why we have that file...

It hasn't changed since Stefanus added it in 2012 (https://github.com/cplusplus/draft/commit/4e08c317690a6013a3daa0dbe95acb5273cd317b#diff-9cc7be2307e175136de8adbd1cafeba5). I suspect it was added by mistake, and we could remove it.

**Pull request closed without merging**
