### PR TITLE
Grammatical improvement; NFC intended

### PR DESCRIPTION
**Pull request by AaronBallman**
I think this is an editorial improvement to the wording, but if it's not editorial, or if I've mucked something up, please let me know.

### CODE REVIEW

**Comment by jwakely** [comment]
LGTM but should it also be "like a non-explicit-constructor" rather than "like non-explicit-constructors" ?

**Comment by AaronBallman** [comment]
That seems like a reasonable suggestion. I'll make that change as well. Thanks!

**Comment by AaronBallman** [comment]
Uncertain if I did the correct git dance, but I *think* this pull request now contains both of my modification. If not, I can try again. :-)

**Comment by zygoloid** [comment]
We have an in-flight core issue that modifies this wording (http://wiki.edg.com/twiki/pub/Wg21lenexa/DraftingReviewTeleconference2015-04-06/proposed_resolution_core-1978.html); I'd like to defer this change until after it lands.

**Comment by AaronBallman** [comment]
Works for me! We can figure out what to do in Lenexa.

**Pull request closed without merging**
