### PR TITLE
P2351: add [[nodiscard]] to cast-like library wrappers [WIP]

### PR DESCRIPTION
**Pull request by hanickadot**
bit_cast, to_integer, forward, move, move_if_noexcept, as_const, to_underlying, and identity::operator()

### CODE REVIEW

**Comment by jensmaurer** [comment]
Which part is "WIP" here?

**Comment by hanickadot** [comment]
Paper is WIP. LEWG is discussing if the paper is worth of spending time on it. My idea is to have an open pull request as part of the paper. If that's not what you want here close it.

**Comment by jensmaurer** [comment]
@tkoeppe, please state whether you consider the change here editorial.
(My view: There is no general or specific guidance from LWG / LEWG for this matter, so this doesn't feel editorial.)

**Comment by hanickadot** [comment]
No, I don't think this is editorial (as much I would like to). I want guidance from LEWG/LWG too. But I also like the idea that the paper is accompanied with an open pull request to the draft. To make it easier for editors.

**Comment by jwakely** [comment]
More specifically, because of https://isocpp.org/std/standing-documents/sd-9-library-evolution-policies, which set the policy.

**Pull request closed without merging**
