### PR TITLE
[locale.numpunct,locale.moneypunct] Canonicalize local grammar presen…

### LINKED ISSUE #3100: fix [locale.numpunct] to use the same presentation for its grammar as the rest of the standard
> The syntax for number formats is as follows, where `digit` represents the radix set specified by the `fmtflags` argument value, and `thousands-sep` and `decimal-point` are the results of corresponding `numpunct<charT>` members. Integer values have the format:
> ```
>     integer ::= [sign] units
>     sign ::= plusminus
>     plusminus ::= ’+’ | ’-’
>     units ::= digits [thousands-sep units]
>     digits ::= digit [digits]
> ```
> [...]

This notation is defined nowhere and is different from how we represent all our other grammars. It also got copied into P0645R10 (2019-07 LWG Motion 5), but I'm fixing that as part of applying the motion.

### PR DESCRIPTION
**Pull request by jensmaurer**
…tation.

Fixes #3100.

### CODE REVIEW

**Comment by jwakely** [comment]
The change looks good to me, but if you're changing this anyway how about addressing two pre-existing issues.

Why do we have "integer" and "floatval" rather than "intval" and "floatval" or something like that?

Why do we need `plusminus`? Can't we just define `sign` as one of `+` and `-`?

Does it matter that _sign_ and _units_ are defined as part of the _integer_ grammar, but used in the _floatval_ one?

**Comment by jensmaurer** [comment]
Fixed the two issues mentioned in the bullets. Leaving the "sign" and "units" issue as-is; the two grammar snippets are right next to each other.

**Comment by jensmaurer** [comment]
Leaving for @zygoloid to apply.

**Comment by zygoloid** [comment]
After rebasing, could you attach an image of the "after" presentation? Thanks!

**Comment by jensmaurer** [comment]
Rebased. Here are the pictures:
numpunct
money

**Pull request merged**
