### PR TITLE
[utility] shorten stable names

### LINKED ISSUE #794: Stable names in 20.11 are too long
[memory.polymorphic.allocator.class]
[memory.resource.monotonic.buffer.ctor]

Surely we can abbreviate these.

### PR DESCRIPTION
**Pull request by jensmaurer**
memory.resource -> mem.res
optional.bad_optional_access -> optional.badaccess
memory.polymorphic -> mem.poly
func.searchers -> func.search
... boyer_moore -> ... bm
... boyer_moore_horspool -> ... bmh

Fixes #794.

### CODE REVIEW

**Comment by tkoeppe** [comment]
I like it. Will leave to @zygoloid to make the final call.

**Comment by jlaire** [comment]
`optional.bad.access` would be like the existing `variant.bad.access`

**Comment by timsong-cpp** [comment]
"memory.polymorphic" is always followed by ".allocator". Why not shorten all three to "mem.poly.alloc"?

**Comment by sigfpe** [comment]
What is wrong with leaving it as is?
-------- Original message --------From: timsong-cpp <notifications@github.com> Date: 11/15/16  6:11 PM  (GMT-08:00) To: cplusplus/draft <draft@noreply.github.com> Subject: Re: [cplusplus/draft] [utility] shorten stable names (#1048) 
"memory.polymorphic" is always followed by ".allocator". Why not shorten all three to "mem.poly.alloc"?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cplusplus/draft","title":"cplusplus/draft","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cplusplus/draft"}},"updates":{"snippets":[{"icon":"PERSON","message":"@timsong-cpp in #1048: \"memory.polymorphic\" is always followed by \".allocator\". Why not shorten all three to \"mem.poly.alloc\"?"}],"action":{"name":"View Pull Request","url":"https://github.com/cplusplus/draft/pull/1048#issuecomment-260833067"}}}

**Comment by jensmaurer** [comment]
We have ".allocator" parts elsewhere, so it seems more consistent to leave them in.

**Pull request merged**
