### PR TITLE
[macros] Remove terms-and-definitions entries from TOC and bookmarks

### PR DESCRIPTION
**Pull request by tkoeppe**
Following the approach of http://stackoverflow.com/a/2785740.

### CODE REVIEW

**Comment by jwakely** [comment]
It would be nice to update the preceding comment, "For ISO format use:"

**Comment by jwakely** [comment]
Maybe remove the comment entirely. The commented-out `\newcommand` is old, and with this proposed change the comment "For ISO format use:" doesn't apply to the line that follows it.

**Comment by tkoeppe** [comment]
@jwakely: Done. As a drive-by, I also made the line break starred so we won't get a page break there.

**Comment by jwakely** [comment]
I've adopted this for the Networking TS (https://github.com/cplusplus/networking-ts/commit/eec1cc947748563e37c62d3fd7e519e66011e156)

**Comment by tkoeppe** [comment]
This change has the unfortunate effect of changing references from "3.x" to just "3".

@zygoloid, @jwakely: I'll look into this and will try to find a better solution that restores the references. I'll be in touch.

**Comment by tkoeppe** [comment]
@jwakely: I changed the way I suppress the TOC entry in 7542c70e0647923d54e8a4d47ea4c9bad4f0072e, which is a superior solution. The first solution did not only break reference labels, but also modified the vertical layout slightly.

**Pull request merged**
