### PR TITLE
[vector.bool.pspc] Add a blank line between the private and public members of std::vector<bool>::reference

### PR DESCRIPTION
**Pull request by blackteahamburger**

### CODE REVIEW

**Comment by tkoeppe** [comment]
This seems rather piecemeal. Similar newlines are missing in other places, even in containers.tex. Could you have a broader look?

**Comment by blackteahamburger** [comment]
> This seems rather piecemeal. Similar newlines are missing in other places, even in containers.tex. Could you have a broader look?

I've done some, please help find more.

**Comment by tkoeppe** [comment]
Could we maybe have one commit per file, and you can combine label references like `[foo.bar, foo.xyz] Tweak vertical whitespace`.

**Comment by blackteahamburger** [comment]
> Could we maybe have one commit per file, and you can combine label references like `[foo.bar, foo.xyz] Tweak vertical whitespace`.

OK. But there are so many of them, can I just write like [ranges]?

**Comment by tkoeppe** [comment]
Yes, some deepest common ancestor is fine.

**Pull request merged**
