### PR TITLE
Update container advice

### PR DESCRIPTION
**Pull request by tvaneerd**
Still somewhat out of date, but better.

### CODE REVIEW

**Comment by timsong-cpp** [comment]
This whole paragraph has no normative impact and should be removed outright or at best turned into a note.

**Comment by tvaneerd** [comment]
Or remove the rest and just leave my Seuss-ism. :-)

**Comment by jfbastien** [comment]
Seuss note sounds good IMO.

**Comment by jensmaurer** [comment]
Please add [sequence.reqmts] (the subclause that is changed) to the start of your commit message. Please turn p2 into a note instead of adding semi-funny normative statements.

**Comment by rmpowell77** [comment]
Sorry to be a pest, but if we remove the rest, then what is best?
Best leave the rest, to stress the best.
Should we add a test?  To invest and stress?
Maybe a random test?  A guess-fest test?
Open that test?  A guest guest-fest test?
Decorate that test?  A dressed guest guess-fest test?

This thread is vest(ed) and gone west.

**Pull request merged**
