### PR TITLE
Update the description for array.data

### PR DESCRIPTION
**Pull request by mclow**
Make it match the one for `vector`.
Compare [vector.data]/1 with the proposed [array.data]/1

### CODE REVIEW

**Comment by jwakely** [comment]
LGTM. Note that [array.zero] covers the empty (N==0) case.

**Comment by tkoeppe** [comment]
This seems legit. The current phrasing is unfortunate in that the single-pass reading requires UB for the `addressof(front())` case, and you don't find out until later that that case is actually different. The proposed change makes it rather clear where you can go if you care about size zero.

**Comment by mclow** [comment]
> Note that [array.zero] covers the empty (N==0) case.

Almost. This section codifies that `[data(), data() + size())` is a valid range, for all sizes.

**Comment by mclow** [comment]
I wish we could find a place to say this in `[string.view]`, but I think that would NOT be editorial.

**Comment by jwakely** [comment]
Right, I should have said that [array.zero] gives the exception to the `data() == addressof(front())` rule. I think the proposed change is an improvement because we don't imply it's undefined (due to calling `front()`), then change our mind later in [array.zero].

**Pull request merged**
