### PR TITLE
[LWG motion 25] P1383R2 More constexpr for cmath and complex

### LINKED ISSUE #6311: [2023-06 LWG Motion 25] P1383R2 More constexpr for cmath and complex
https://wiki.edg.com/pub/Wg21varna/StrawPolls/P1383R2.pdf

### PR DESCRIPTION
**Pull request by burblebee**
Fixes #6311.
Fixes cplusplus/papers#168

### CODE REVIEW

**Review by JohelEGP — APPROVED** [review]
I'm using <https://isocpp.org/files/papers/P1383R2.pdf>.

**Comment by JohelEGP** [comment]
Looks like `__cpp_lib_constexpr_cmath` wasn't bumped by the paper.

**Comment by PJBoy** [comment]
Shall we let burblebee commit a bump as part of this PR or should I raise a new issue?

**Comment by jwakely** [comment]
LWG motion 5 was missing a macro bump too

**Comment by jensmaurer** [comment]
@burblebee , please bump `__cpp_lib_constexpr_cmath` in a separate commit of this pull request.

**Comment by tkoeppe** [comment]
Feature test macro bumped, thanks!

**Pull request merged**
