### PR TITLE
(may be wrong) [tuple.apply] Use existing std::invoke function rather than magic INVOKE

### PR DESCRIPTION
**Pull request by tkoeppe**

### CODE REVIEW

**Comment by K-ballo** [comment]
I believe this might not be editorial as `std::invoke` is not constexpr? That seems a bit inconsistent though.

**Comment by tkoeppe** [comment]
Oh god, right. Why isn't it constexpr? And why isn't it appropriately noexcept? :-(

**Comment by K-ballo** [comment]
Beats me. I think the lack of `constexpr` deserves an issue, it's inconsistent with `apply`. As for `noexcept`, implementations might add those if they wish to do so.

**Comment by tkoeppe** [comment]
[N4169](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4169) discusses `constexpr`.

**Comment by AlisdairM** [comment]
I believe we had this discussion when designing the feature for the TS, and the current design of using the INVOKE magic was deliberately chosen, as it provides all the necessary magic without accidentally mis-specifying a subtle language feature in the function signature - any change here should definitely go through a working group.

That said, I think there was some interest in cleaning the magic out of the standard once 'std::invoke' landed - although it would definitely require a paper to happen, and may be more subtle than expected.  I got burned in the past trying to clean up mem_fn, for example.

**Comment by tkoeppe** [comment]
@AlisdairM: Thanks, that's good to know. I might just close this PR then and we leave the wording as is.

**Comment by AlisdairM** [comment]
I should add that I am tentatively in favor of such a paper that I have no plans to write myself ;)  I do think it will be a non-trivial amount of work to get right though - we still need better language support for forwarding functions that implicitly preserve the properties of what they are forwarding to.

**Comment by tkoeppe** [comment]
OK, noted :-)

**Pull request closed without merging**
