### PR TITLE
[class.pre] Fix incorrect comment in example

### PR DESCRIPTION
**Pull request by jensmaurer**
Partially addresses #4592

### CODE REVIEW

**Comment by tkoeppe** [comment]
@opensdh: could you please take a look?

**Comment by opensdh** [comment]
I [commented](https://github.com/cplusplus/draft/issues/4592#issuecomment-859718676) on the issue already.

**Comment by tkoeppe** [comment]
@opensdh: OK, thanks! So we take this PR as a partial improvement, but I'll leave it to you (= collectively) to come up with a more comprehensive example?

**Comment by opensdh** [comment]
If it's up to me, we'd make the full change I suggested in one go, since @xmh0511 correctly pointed out that merely correcting the example leaves it a bit mysterious (apparently misplaced).  I can always do the rest later, though, since some more work is already needed (as also noted).

**Comment by tkoeppe** [comment]
Thanks. I agree that we should get the full rewrite, but let's take this partial fix for now so that we're at least not saying anything wrong, even if it's mysterious. But I continue looking forward to the full solution!

**Pull request merged**
