### PR TITLE
P0646R1 Improving the return value of erase-like algorithms

### LINKED ISSUE #2143: [2018-06 LWG Motion 26] P0646R1 Improving the return value of erase-like algorithms

### PR DESCRIPTION
**Pull request by jwakely**
Fixes #2143

### CODE REVIEW

**Comment by jensmaurer** [comment]
Feature test macro: __cpp_lib_list_remove_return_type

**Comment by jwakely** [comment]
Looks like I used D0646R1 instead of the one from the straw polls page (which was dumb, as I wrote the Annex C wording so should have noticed it was missing). I'll push a commit to the branch ...

**Comment by jwakely** [comment]
Done.

**Comment by jensmaurer** [comment]
Uh, @jwakely: The commits should use sentence case, not title case, even if the paper title erred in that regard. Not sure how to fix that without a force-push, though.

**Comment by jwakely** [comment]
I forgot that rule and did a copy&paste from the paper title, sorry.

**Comment by tkoeppe** [comment]
This isn't the end of the world. The application to master is a rebase
anyway at which point we can rename anything we like.

**Comment by jensmaurer** [comment]
@tkoeppe Right, but will @zygoloid remember this particular case?

**Comment by zygoloid** [comment]
Yes, @zygoloid reads these threads while rebasing and merging :)

**Comment by zygoloid** [comment]
Minor adjustments made while merging: changed restrictive "which" to "that" in Annex C, replaced `\_` with `_` (we use the textunderscore package), replaced "C++" with "\Cpp{}" macro in Annex C.

**Pull request merged**
