### PR TITLE
[cmp.categories.pre] Remove unused enumerators

### LINKED ISSUE #3541: [cmp.categories.pre] nonequal and nonequivalent are non-used
After [P1959R0](https://wg21.link/P1959R0) "Remove `std::weak_equality` and `std::strong_equality`" was adopted, [N4842](https://wg21.link/N4842) [17.11.2.1 [cmp.categories.pre]/1](https://eel.is/c++draft/cmp.categories.pre#1) says:

> Each is specified in terms of an exposition-only data member named `value` whose value typically corresponds to that of an enumerator from one of the following exposition-only enumerations:
> `enum class` *`eq`* `{` *`equal`* `= 0,` *`equivalent`* `=` *`equal`*`,` *`nonequal`* `= 1,` *`nonequivalent`* `=` *`nonequal`* `};` *// exposition only*

However, *`nonequal`* and *`nonequivalent`* are now unused. As they're exposition-only enumerators, they should be editorially removed.

### PR DESCRIPTION
**Pull request by CaseyCarter**
Fixes #3541.

### CODE REVIEW

**Comment by zygoloid** [comment]
Do we still need the `eq` enum at all? Perhaps we could merge it into `ord`?

**Comment by CaseyCarter** [comment]
> Do we still need the `eq` enum at all? Perhaps we could merge it into `ord`?

Yes, this is feasible: `eq` is only used as a constructor parameter type, and the classes with such a constructor already have a constructor that takes `ord`.

**Comment by tkoeppe** [comment]
@jensmaurer: sorry, I missed that ping; I agree that a more aggressive cleanup is a nice idea.

**Comment by CaseyCarter** [comment]
I've made the requested changes.

**Comment by jwakely** [comment]
We don't really need the `equal` enumerator either, it's used in exactly one place and we could just use `equivalent` there. It might even make it clearer that equivalence is the same as equality for `strong_ordering`.

**Comment by CaseyCarter** [comment]
> We don't really need the `equal` enumerator either, it's used in exactly one place and we could just use `equivalent` there. It might even make it clearer that equivalence is the same as equality for `strong_ordering`.

I'd vaguely prefer to keep the `equal` vs. `equivalent` distinction to reflect "substitutability", but it's not a hill I'm willing to die on.

**Comment by jwakely** [comment]
OK, I don't feel strongly about it either.

**Comment by CaseyCarter** [comment]
Ping. Could someone please remove the changes-requested label so this is visible again?

**Comment by jensmaurer** [comment]
Done.

**Pull request merged**
