### PR TITLE
[swappable.requirements] Merge example's comment to one line

### PR DESCRIPTION
**Pull request by johelegp**
This follows the style of the surrounding comments.

### CODE REVIEW

**Comment by tkoeppe** [comment]
I think I'd rather just get rid of the pointless line break, non?

**Comment by johelegp** [comment]
Of the surrounding comments, if that was done to the one below, it would merge the comments. Although it can be done for the one in the fix and the one above it, the current style is most general. What do you think? Do we keep the one below and remove them from the two above.

**Comment by johelegp** [comment]
```C++
  swap(t1, t2);     // OK: uses swappable conditions for lvalues of type \tcode{T}
```
Oh, you mean like that?

**Comment by tkoeppe** [comment]
Yes.

**Comment by johelegp** [comment]
Done.

**Comment by tkoeppe** [comment]
Thanks!

**Comment by jensmaurer** [comment]
Looks good to me.

**Comment by tkoeppe** [comment]
Oh, wait, this would overrun the line, right? Can you render it and see what it looks like? I didn't realize how far out the comment is. If it doesn't fit, let's go back to the original proposal.

**Comment by johelegp** [comment]
I'll try rendering it. I think I've never done it before. However, I thought it was fine by looking at the code, as the comment's font should be mostly shorter than the code's monospaced font.

**Comment by johelegp** [comment]
Actually, I just assumed it wouldn't fit, but it does. Now I know I should render in these cases.

**Comment by tkoeppe** [comment]
No, let's not do that, because the overall consistency with the remainder of the code makes it preferable to keep all the comments at the same column. Your original proposal was good.

**Comment by tkoeppe** [comment]
Oh, does it actually fit? Great.

**Comment by jensmaurer** [comment]
I just tried it out locally; the change does not cause an overfull hbox.

**Comment by tkoeppe** [comment]
@jensmaurer: That's not relevant, though: what matters is that there isn't a line break. Long comments will happily go on as many lines as they need, all neatly justified.

**Pull request merged**
