### PR TITLE
[expected.object.general] Remove explicit(see below) for expected copy/move constructor

### PR DESCRIPTION
**Pull request by hewillk**

### CODE REVIEW

**Review by jensmaurer — APPROVED** [review]
These are mistakes in the plenary-approved paper http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p0323r12.html#expected.expected

**Comment by jensmaurer** [comment]
@jwakely , any concerns?

**Comment by JohelEGP** [comment]
The commit message is missing the reference to `expected.void.general`, like #5424.

**Comment by jensmaurer** [comment]
@CaseyCarter , @jwakely, any concerns about this one?

**Comment by CaseyCarter** [comment]
This is exactly the change that #5424 made.

**Review by CaseyCarter — APPROVED** [review]

**Comment by jensmaurer** [comment]
@jwakely , I'd appreciate your approval here.

**Review by jwakely — APPROVED** [review]

**Comment by jwakely** [comment]
I think these were misplaced in the synopses, they should have been on *these* constructors instead:

```c++
template<class G>
  constexpr expected(const unexpected<G>&);
template<class G>
  constexpr expected(unexpected<G>&&);
```

See [LWG 3754](https://wg21.lwg3754) which wants to add them to those constructors.

**Comment by hewillk** [comment]
The link is invalid.

**Pull request merged**
