### PR TITLE
[dcl.dcl][stmt.stmt] Remove tautonyms from top level stable labels

### PR DESCRIPTION
**Pull request by AlisdairM**
Per comment on issue #5315.
Thanks to Jonathan Wakely for the notion of tautonyms.

Quickly force-pushed a correction to the comment identifying the PR number.

### CODE REVIEW

**Review by jensmaurer — APPROVED** [review]
I like that.

**Comment by jensmaurer** [comment]
One check-output.sh error remains:

2024-07-28T21:03:49.8853617Z incorrect entries in xrefdelta.tex:
2024-07-28T21:03:49.8867284Z spurious diff.cpp23.dcl.dcl

**Comment by AlisdairM** [comment]
Silly mistake corrected --- there is no diff.cpp23 in the C++23 standard itself!

**Comment by AlisdairM** [comment]
Has this missed the clause revisions for C++26?

**Comment by tkoeppe** [comment]
I'm not sure about this change yet, let's discuss at the meeting.

**Comment by AlisdairM** [comment]
Squashed, rebased, and force-pushed for good measure.

**Comment by tkoeppe** [comment]
Let's go with Jen's approach and leave the diff labels alone. We're causing enough upset as it is.

**Pull request closed without merging**
