### PR TITLE
[std] Switch grammar to  \sffamily \itshape

### LINKED ISSUE #323: grammar terms are indistinguishable from defined terms
This issues was raised by Gaby - that you can't tell definitions from grammar terms, because both are _italics_.  Maybe use **_bold italics**_ for one of those - like the definition?

### PR DESCRIPTION
**Pull request by jensmaurer**
Fixes #323.

### CODE REVIEW

**Comment by jensmaurer** [comment]
Also do a visual diffpdf.

**Comment by jensmaurer** [comment]
Fix 9.5.4 promise-comstructor-arguments formatting, rename to $A$.

**Comment by Eelis** [comment]
Does this patch preserve the regex grammar typesetting in [re.grammar]? Per https://github.com/cplusplus/draft/pull/3193, the grammar typesetting in that subclause should be consistent with the regex grammar typesetting in the upstream ECMAScript standard.

**Comment by jensmaurer** [comment]
@Eelis: Yes, I've tried hard.

**Comment by jensmaurer** [comment]
Editorial meeting: @tkoeppe to investigate other font choices in the next days.

**Comment by jensmaurer** [comment]
@tkoeppe , any results from your investigation?

**Comment by tkoeppe** [comment]
Yes, the various alternatives I had considered all don't really look any better. Give me another day or two to be sure, but we'll probably keep the initial proposal.

**Comment by tkoeppe** [comment]
Let's proceed with what we have. I haven't found any alternatives that are clearly superior. DejaVu Sans is quite nice and has a condensed version (and needs to be scaled to 80%), but the difference with Latin Modern's version is rather minor. The ease of setup of the current solution is compelling, and we can iterate on minor variations later on.

**Pull request merged**
