### PR TITLE
[macros] Allow \keyword and \grammarterm in section headings

### PR DESCRIPTION
**Pull request by jensmaurer**
by disabling all indexing when typesetting the table-of-contents.

### CODE REVIEW

**Comment by JohelEGP** [comment]
Does this also mean that `\cname` is no longer necessary?

**Comment by jensmaurer** [comment]
We could apply the approach to `\libconcept`, too, and thus replace `\cname` with `\libconcept` in section headings, yes.

**Comment by tkoeppe** [comment]
(This actually changes surprisingly little; I suppose most keywords in headings are already indexed in the subsequent text.)

**Comment by tkoeppe** [comment]
Ah yes, of course: the change _does_ add new indexing, just not in the TOC.

**Pull request merged**
