### PR TITLE
Convert blah\opt to \opt{blah}

### LINKED ISSUE #1433: Review use of \xspace in macro definitions
See http://tex.stackexchange.com/questions/86565/drawbacks-of-xspace with the first answer from the package author of \xspace. Quote:

> So, if you find it useful, fine, it's there. But personally I wouldn't recommend it.

\xspace in \grammarterm caused spacing issues while addressing #1268.

### PR DESCRIPTION
**Pull request by jensmaurer**
Fixes #1433.

### CODE REVIEW

**Comment by jensmaurer** [comment]
No diffs in diffpdf "words" mode; two expected line-breaking diffs in "appearance mode" for the C++ 20nn non-breaking space.

I can squash some of these commits if desired.

**Comment by tkoeppe** [comment]
I stole a few commits I liked from this PR. Please rebase.

**Comment by jensmaurer** [comment]
Rebased.

After @tkoeppe's partial merge, the remaining change is to morph blah\opt into \opt{blah}.

**Comment by tkoeppe** [comment]
Is the "C++ 2003" change worth it? Either we already don't break the line, or if we need to break, it doesn't look like a terrible place to break. Why prevent the line break at all costs?

**Comment by jensmaurer** [comment]
@tkoeppe: That's why it is a separate commit.

In my view, it's somewhat ugly to have "C++" at the end of a line and then have the next line start with "2003". And in the two situations where it makes a difference, TeX find another linebreak opportunity. Maybe it's better to apply some extra penalty as opposed to "prevent at all costs", though.

**Comment by tkoeppe** [comment]
Yes, if we could "discourage" rather than "forbid absolutely", that'd be nice. I.e. it's good if we can *improve* the situation without *breaking* it.

**Comment by jensmaurer** [comment]
Dropped patch for avoiding line breaks for earlier versions of C++.

**Comment by jensmaurer** [comment]
@zygoloid : This merge went the wrong way: You merged "master" into my branch, it seems, rather than the other way round.

**Comment by tkoeppe** [comment]
@jensmaurer: No, I think he was trying to rebase your PR. Apparently that's a thing you can do now.

**Comment by jensmaurer** [comment]
@tkoeppe: Ahem. I thought "rebases" don't want to do a "merge", but a force-push, to keep the history clean?

**Comment by jensmaurer** [comment]
Ah, the \tilde changes. Let me fix those in a proper rebase and push again.

**Comment by tkoeppe** [comment]
No visual diff, looks good. Will leave to @zygoloid to merge because of the wide impact.

**Pull request merged**
