### PR TITLE
[fs.class.filesystem_error] Rephrase para 1 to avoid "class defines t…

### PR DESCRIPTION
**Pull request by CaseyCarter**
…ype"

### CODE REVIEW

**Comment by jensmaurer** [comment]
I support this change; it's a net improvement. But [res.on.exception.handling] already discusses derived classes; it would be good to defer the exact set of types that could be thrown to that section. Also, [except.handle] explains that only unambiguous public base classes fit, so something like
`class D : private filesystem_error { };`
is not suitable (but fits the wording as proposed).

**Comment by tkoeppe** [comment]
@jensmaurer: Do you want a more extensive change here, or is it OK as is?

**Comment by jensmaurer** [comment]
@tkoeppe: The proposed wording is not ok; it incorrectly handles private and ambiguous base classes.

**Comment by CaseyCarter** [comment]
> The proposed wording is not ok

+1, this is broken and I need to fix it. Actually, I'll just close the PR until I have new wording.

**Pull request closed without merging**
