### PR TITLE
[utility.intcmp] Remove Mandates implied by Equivalent to

### LINKED ISSUE #5007: [utility.intcmp].9 is redundant
https://wg21.link/utility.intcmp#9 is implied by the "Equivalent to:" semantics.

### PR DESCRIPTION
**Pull request by JohelEGP**
Resolves #5007.

### CODE REVIEW

**Comment by timsong-cpp** [comment]
This was discussed in Prague. LWG wasn't satisfied that `numeric_limits<R>::min()` is guaranteed to be of type `R`, given that it is entirely unclear what the requirements on user specializations are.

**Comment by JohelEGP** [comment]
Doesn't https://eel.is/c++draft/library#contents-3 prevent ADL? Or is it to allow some two-step dance as with `std::swap`?

**Comment by timsong-cpp** [comment]
The point is that we want to ban `in_range<Meow>(42)` even if `numeric_limits<Meow>::min()` is an `int`.

**Comment by JohelEGP** [comment]
Makes sense. Thank you.

**Pull request closed without merging**
