### PR TITLE
[iterators] Add missing definitions from the iterators library to the library index

### PR DESCRIPTION
**Pull request by Ukilele**
Add following definitions from the iterators library to the library index:

- indirect_result_t
- iter_common_reference_t
- iter_const_reference_t 
- iter_reference_t
- iter_rvalue_reference_t
- make_const_iterator
- make_const_sentinel

### CODE REVIEW

**Review by JohelEGP — CHANGES_REQUESTED** [review]
Using `\libglobal` instead of `\indexlibraryglobal` should index to the correct page, and raise the confidence by inspection that we're not indexing into a definition that says _`see below`_.

**Comment by Ukilele** [comment]
Hi @JohelEGP , thanks a lot for your feedback. So is it `\libglobal` instead of `\indexlibraryglobal` for all of the definitions that I cover in my PR? I am uncertain, because I think none of the indexes are indexing into a definition that says `see below`.

**Comment by JohelEGP** [comment]
> So is it `\libglobal` instead of `\indexlibraryglobal` for all of the definitions that I cover in my PR?

That's right.

> I am uncertain, because I think none of the indexes are indexing into a definition that says `see below`.

I'd have to manually check if you're right. But if you used `\libglobal`, any _`see below`_ would be in the context of the difference, which would make reviewing a breeze.

**Review by JohelEGP — APPROVED** [review]

**Comment by Ukilele** [comment]
Obviously this is my first contribution. I am very thankful for your helpful and especially very quick support, @JohelEGP . Thank you very much!

**Comment by JohelEGP** [comment]
You can fixup the commits into a single one formatted as described at https://github.com/cplusplus/draft/wiki/Commit-message-format#editorial-commits.

**Review by JohelEGP — APPROVED** [review]

**Review by jensmaurer — APPROVED** [review]

**Review by jensmaurer — CHANGES_REQUESTED** [review]
Please fix the merge conflicts.

**Comment by tkoeppe** [comment]
@jensmaurer Can you reapprove?

**Review by jensmaurer — APPROVED** [review]

**Comment by jensmaurer** [comment]
@tkoeppe, I can.

**Comment by tkoeppe** [comment]
Thanks, Jens, esp. for avoiding undefined modal verbs.

@Ukilele Thank you very much for your contribution!

**Pull request merged**
