### PR TITLE
[dcl.spec.general,dcl.fct.spec] Clarify duplication of decl-specifiers

### LINKED ISSUE #4796: [dcl.spec.general] p2 prevents the valid type combination
````cpp
unsigned  long  long int const volatile a = 0;
````
In this declaration, the complete decl-specifier-seq is `unsigned  long  long int const volatile`. Where *unsigned*, *long*, *long*, *int* are all *simple-type-specifier*s, which in turn are *type-specifier*s, which are also *defining-type-specifier*s; While *const* and *volatile* are both *cv-qualifier*s, which are *type-specifier*s, which are also *defining-type-specifier*s. Hence, in this complete  *decl-specifier-seq*, the defining-type-specifier appears six times. 

However, [dcl.spec.general] p2 says  
> Each decl-specifier **shall** appear at most once in a complete decl-specifier-seq, except that long may appear twice.

Obviously, *defining-type-specifier* appears more than once that are not only *long*.   I think the intent of this rule says each indivisible specifier shall appear at most once except that *long* may appear twice, I would like to name the indivisible specifier as **atomic** specifier(e.g., int, long, short, const, virtual, explicit ...). But It's not formal wording, maybe we can use some terms to precisely phrase such the meaning?

### PR DESCRIPTION
**Pull request by jensmaurer**
Fixes #4796

### CODE REVIEW

**Comment by tkoeppe** [comment]
This looks reasonable, but  I would welcome a quick Core cross-check, given the ever-increasing complexity of decl-specifiers.

**Comment by jensmaurer** [comment]
Put onto core's inbox: https://wiki.edg.com/bin/view/Wg21telecons2021/CoreWorkingGroup

**Comment by tkoeppe** [comment]
CWG meeting consensus Nov 11: This is an improvement. We acknowledge that this wording strategy comes with a maintenance burden, but it's better than the status quo.

**Comment by jensmaurer** [comment]
@tkoeppe, what are we  waiting for with this fix?

**Comment by tkoeppe** [comment]
I think it's fine to go, thanks!

**Pull request merged**
