### PR TITLE
Unify typesetting of ordinals.

### PR DESCRIPTION
**Pull request by godbyk**
This PR unifies the typesetting of ordinals per the guidance provided in issue #653.

### CODE REVIEW

**Comment by W-E-Brown** [comment]
> On May 11, 2018, at 5:58 PM, Kevin Godby <notifications@github.com> wrote:
> 
> This PR unifies the typesetting of ordinals per the guidance provided in issue #653.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/cplusplus/draft/pull/2071
> 
> Commit Summary
> 
> 	• Unify typesetting of ordinals.
> File Changes
> 
> 	• M source/classes.tex (2)
> 	• M source/containers.tex (2)
> 	• M source/declarators.tex (12)
> 	• M source/numerics.tex (20)
> 	• M source/overloading.tex (4)
> 	• M source/templates.tex (10)
> 	• M source/utilities.tex (6)
> Patch Links:
> 
> 	• https://github.com/cplusplus/draft/pull/2071.patch
> 	• https://github.com/cplusplus/draft/pull/2071.diff

This proposed patch seems to me to go beyond unifying typesetting.

The typesetting changes seem fine, but changing "st" to "th" in some ordinal expressions seems not okay, especially without drawing attention to such.  I these adjustments as not at all a purely typesetting matter.

There's no English word "oneth"; we say "first" instead.  While I know that some (mostly non-mathematicians) disagree, the ordinal version of "m+1" is pronounced "m plus first" rather than "m + oneth"; therefore, please revert the corresponding parts of this proposed patch and restore "st" as the superior characters in these cases.  (See line 1578 of file source/overloading.tex for one example; there are several more in the proposed patch.)

And yes, if we had ordinal versions of "m+2" or "m+3" I would want the corresponding superior characters to be "nd" and "rd", respectively; there's no modern English "twoth" or "threeth" AFAIK.

**Comment by godbyk** [comment]
@W-E-Brown I restored the two `st` ordinals in `overloading.tex`. As far as I noticed, they were the only two there. Did you notice any other instances?

**Comment by W-E-Brown** [comment]
> On May 11, 2018, at 8:46 PM, Kevin Godby <notifications@github.com> wrote:
> 
> @W-E-Brown I restored the two st ordinals in overloading.tex. As far as I noticed, they were the only two there. Did you notice any other instances?

I had thought there were some in numerics, but I don't now see any there.  Thank you.

**Comment by zygoloid** [comment]
For posterity: I was curious why we're changing from `\textrm` and `\mathrm` to `\text`, and what the differences between them are. That led me to this: https://tex.stackexchange.com/questions/70632/difference-between-various-methods-for-producing-text-in-math-mode -- from which I conclude that `\text` (+ the `amsmath` package, which we already use) is the best choice.

**Pull request merged**
