### PR TITLE
P2874R2 Mandating Annex D

### LINKED ISSUE #6305: [2023-06 LWG Motion 19] P2874R2 Mandating Annex D

### PR DESCRIPTION
**Pull request by AlisdairM**
Applies all changes to replace 'requires' clauses in Annex D with more modern wording, per LWG Poll 19 at Varna 2023 meeting, paper P2874R2.

Fixes #6305
Fixes cplusplus/papers#1557

### CODE REVIEW

**Comment by tkoeppe** [comment]
You should assign the tracking issue #6305 to yourself to make sure nobody duplicates this work!

**Comment by jensmaurer** [comment]
Please fix xrefdelta.tex:

incorrect entries in xrefdelta.tex:
missing depr.res.on.required
Error: Process completed with exit code 1.

**Comment by jwakely** [comment]
The changes to the actual text look OK to me, once the error is fixed.

**Comment by AlisdairM** [comment]
Sorry, under the weather and slow to reply.
The reason I did not immediately fix the removed stable tag entry is that I am not sure how best to proceed.  That index is relative to C++20, so should we be resetting it for C++23, or continuing to expand the reference since C++20?

**Comment by jensmaurer** [comment]
The editor should reset the stable tag reference to C++23. @tkoeppe

**Review by JohelEGP — APPROVED** [review]

**Comment by tkoeppe** [comment]
I'll update xrefdelta after the motions, thanks!

**Pull request merged**
