### PR TITLE
[print.syn] Show `locking` functions in the synopsis of `<print>`

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
The changes seem missed in #6908.

### CODE REVIEW

**Comment by frederick-vs-ja** [comment]
Currently there're no
- `void vprint_unicode_locking(string_view fmt, format_args args);` and
- `void vprint_nonunicode_locking(string_view fmt, format_args args);`

overloads (where `stdout` should be the omitted `FILE*` argument).

Should there be an LWG issue for this? @jwakely @Dani-Hub

**Comment by Dani-Hub** [comment]
> Currently there're no
> 
>     * `void vprint_unicode_locking(string_view fmt, format_args args);` and
> 
>     * `void vprint_nonunicode_locking(string_view fmt, format_args args);`
> 
> 
> overloads (where `stdout` should be the omitted `FILE*` argument).
> 
> Should there be an LWG issue for this? @jwakely @Dani-Hub

I noticed the omission in P3107R5 as well, but it looked deliberate to me. @jwakely What do you think?

**Comment by jwakely** [comment]
We don't want convenience functions for using those with `stdout`. They're low level, internal implementation details. They don't need to be convenient.

**Comment by jensmaurer** [comment]
I notice that the paper P3107R5 did not show a header where to add those _locking functions.

@jwakely , is the change proposed here (not the add-on stdout overloads) editorially-obvious?

**Comment by jwakely** [comment]
Yes, I think the new functions should be in the synopsis.

**Review by jensmaurer — APPROVED** [review]

**Comment by jensmaurer** [comment]
@jwakely , care to approve, then?

**Comment by frederick-vs-ja** [comment]
@tkoeppe @jwakely This PR is outdated due to [P3235R3](https://wg21.link/p3235r3). Could you review the new PR?

**Pull request merged**
