### PR TITLE
[intro.object] For object names, don't refer to 'name' grammar rule, …

### PR DESCRIPTION
**Pull request by Eelis**
…because that one is from [path.generic].

### CODE REVIEW

**Comment by tkoeppe** [comment]
Surely the right thing would be to fix the filesystem grammar name rather than meddle with the fundamental object model?

Also, why doesn't the filesystem grammar get indexed? Maybe it's missing from the list of indexable files.

**Comment by tkoeppe** [comment]
Oh, I see, the grammar in iostreams.tex is "non-copied".

**Comment by Eelis** [comment]
The thing is, as far as I can see, there is no "name" grammar rule other than the one in [path.generic]. So even if we convince ourselves it doesn't really refer to that one, then what _does_ it refer to? :)

**Comment by jwakely** [comment]
For consistency with the rest of the paragaph it should use `\term{name}`, rather than simply dropping all formatting from that word.

**Comment by tkoeppe** [comment]
Yes, I can see that. Maybe the commit should be phrased like https://github.com/cplusplus/draft/commit/5c8435cbf3721eefc02eae58543adc73b51d889f

**Comment by jwakely** [comment]
And clearly it refers to the definition of "name" in Clause 3, as indicated by the cross-reference.

**Comment by Eelis** [comment]
Thanks, that makes sense. Updated branch

**Comment by tkoeppe** [comment]
Much better, thanks!

**Pull request merged**
