### PR TITLE
[xrefdelta] Use \deprxref

### PR DESCRIPTION
**Pull request by jensmaurer**

### CODE REVIEW

**Comment by jensmaurer** [comment]
Rebased.

**Comment by tkoeppe** [comment]
Sorry, could you briefly explain this change? What does it fix or address?

**Comment by jensmaurer** [comment]
It simply uses a macro intended for the purpose instead of open-coding the moved xref. There should be zero change in appearance of the resulting PDF.

**Comment by tkoeppe** [comment]
Ah good, thanks!

**Pull request merged**
