### PR TITLE
P3340R0 A Consistent Grammar For Sequences

### PR DESCRIPTION
**Pull request by AlisdairM**
P3340R0 A Consistent Grammar For Sequences

Fixes https://github.com/cplusplus/draft/issues/7406
Fixes https://github.com/cplusplus/papers/issues/2003

### CODE REVIEW

**Comment by jensmaurer** [comment]
Please fix the commit title and description per https://github.com/cplusplus/draft/wiki/Commit-message-format

**Review by jensmaurer — APPROVED** [review]
Change looks good; title of commit message needs work.

**Comment by AlisdairM** [comment]
Could you confirm that the commit message is now correct, or clarify what needs further correction?

**Comment by jensmaurer** [comment]
Yes, looks good.

**Pull request merged**
