### PR TITLE
[utilities, depr] Replace "member typedef" with "nested type" 

### PR DESCRIPTION
**Pull request by cpplearner**
[class.mem]/3:

> Nested types are classes (12.1, 12.2.5) and enumerations (10.2) declared in the class and arbitrary types declared as members by use of a typedef declaration (10.1.3) or _alias-declaration_.

In most cases there's no normative change because the member must name a pre-existing type.

`aligned_storage` and `aligned_union` are special-cased because their member `type` may name a new type. In particular, `aligned_storage::type` is defined as a nested class type in both libstdc++ and libc++.

### CODE REVIEW

**Comment by jensmaurer** [comment]
In a phrasing like "the member typedef X names ..." or "the member typedef is T", I think this change makes things worse: We know we can't have a fresh type here, so why use a phrasing that allows this?

I agree the change for aligned_storage, aligned_union is good (it's not talking about a pre-existing type), but it seems borderline editorial. (Although it's probably unobservable whether something is a typedef to something else that cannot otherwise be named or is a new type by itself.)

**Comment by cpplearner** [comment]
"Member typedef" is not a defined term, and does not clearly indicate that the member can also be declared using an alias-declaration.

"Nested type" is already used in e.g. [\[container.insert.return\]/1](http://eel.is/c++draft/container.insert.return#1), [\[move.iterator\]/1](http://eel.is/c++draft/move.iterator#1), [\[depr.func.adaptor.typedefs\]/4](http://eel.is/c++draft/depr.func.adaptor.typedefs#4), and in these cases the types have to be synonyms for pre-existing types (or specializations of a pre-existing template).

**Comment by jwakely** [comment]
I think "the nested type `type` names ..." makes things worse. A typedef names another type, a nested type doesn't necessarily.

> does not clearly indicate that the member can also be declared using an alias-declaration

I disagree, since there's no semantic difference between the two. [dcl.typedef] p2 "A _typedef-name_ can also be introduced by an _alias-declaration_."

"Member typedef" seems clear to me, and we do say "typedef member" in [class.mfct]

**Comment by jensmaurer** [comment]
I'd rather replace "nested type", when talking about synonyms, from [container.insert.return]/1, [move.iterator]/1, [depr.func.adaptor.typedefs]/4 than go the other way.

So, in the interest of progress, this pull request could go forward if it would only propose change 7b2c0db.

For the rest, I agree that "member typedef" might be viewed as excluding alias-declarations (although the difference is unobservable, so it doesn't matter). What about "The member X is a synonym for the type T." as the uniform standard phrasing?

**Comment by tkoeppe** [comment]
Feel free to reopen if and when you'd like to address the above issues.

**Pull request closed without merging**
