### PR TITLE
Change stable names for Filesystem subclause

### PR DESCRIPTION
**Pull request by jwakely**
Addresses #1502 

This doesn't change the [class.*] names mentioned in the issue: [class.directory_entry], [class.rec.dir.itr], [class.directory_iterator], [class.file_status], [class.filesystem_status], [class.path]

### CODE REVIEW

**Comment by jensmaurer** [comment]
I would actually prefer to have all stable filesystem labels to start with "fs".

**Comment by jwakely** [comment]
Sure, I can do that.

**Comment by jensmaurer** [comment]
@jwakely: Please get approval from @zygoloid before doing that.

**Comment by zygoloid** [comment]
Yes, let's do it. Please put a mapping table into the commit message (for the editors' report) and let lwgchair know too.

**Comment by zygoloid** [comment]
Please can you rebase?

**Comment by jwakely** [comment]
Working on it.

**Comment by jwakely** [comment]
Rebased. As shown in the commit message, the mappings are:

````
    [class.path] -> [fs.class.path]
    [path.generic] -> [fs.path.generic]
    [path.cvt] -> [fs.path.cvt]
    [path.fmt.cvt] -> [fs.path.fmt.cvt]
    [path.type.cvt] -> [fs.path.type.cvt]
    [path.req] -> [fs.path.req]
    [path.member] -> [fs.path.member]
    [path.construct] -> [fs.path.construct]
    [path.assign] -> [fs.path.assign]
    [path.append] -> [fs.path.append]
    [path.concat] -> [fs.path.concat]
    [path.modifiers] -> [fs.path.modifiers]
    [path.native.obs] -> [fs.path.native.obs]
    [path.generic.obs] -> [fs.path.generic.obs]
    [path.compare] -> [fs.path.compare]
    [path.decompose] -> [fs.path.decompose]
    [path.query] -> [fs.path.query]
    [path.gen] -> [fs.path.gen]
    [path.itr] -> [fs.path.itr]
    [path.non-member] -> [fs.path.nonmember]
    [path.io] -> [fs.path.io]
    [path.factory] -> [fs.path.factory]
    [class.filesystem_error] -> [fs.class.filesystem_error]
    [enum.path.format] -> [fs.enum.path.format]
    [enum.file_type] -> [fs.enum.file_type]
    [enum.copy_options] -> [fs.enum.copy.opts]
    [enum.perms] -> [fs.enum.perms]
    [enum.perm_options] -> [fs.enum.perm.opts]
    [enum.directory_options] -> [fs.enum.dir.opts]
    [class.file_status] -> [fs.class.file_status]
    [file_status.cons] -> [fs.file_status.cons]
    [file_status.obs] -> [fs.file_status.obs]
    [file_status.mods] -> [fs.file_status.mods]
    [class.directory_entry] -> [fs.class.directory_entry]
    [directory_entry.cons] -> [fs.dir.entry.cons]
    [directory_entry.mods] -> [fs.dir.entry.mods]
    [directory_entry.obs] -> [fs.dir.entry.obs]
    [class.directory_iterator] -> [fs.class.directory_iterator]
    [directory_iterator.members] -> [fs.dir.itr.members]
    [directory_iterator.nonmembers] -> [fs.dir.itr.nonmembers]
    [class.rec.dir.itr] -> [fs.class.rec.dir.itr]
    [rec.dir.itr.members] -> [fs.rec.dir.itr.members]
    [rec.dir.itr.nonmembers] -> [fs.rec.dir.itr.nonmembers]
````

**Pull request merged**
