### PR TITLE
[range.as.const.view] Fix constrain order

### PR DESCRIPTION
**Pull request by hewillk**
Make it consistent with the synopsis.

### CODE REVIEW

**Comment by tkoeppe** [comment]
I realize we made this change for as_rvalue_view (2f228c5cad223a5c8d686d91b054ee3bd2d2a123), but on a closer look, I don't think there's any kind of preference in the existing text for either priority. Some view templates start with `view`, others with `input_range`, and this isn't the only outlier. (E.g. look at `join_view`.)

I'd welcome a wider discussion and analysis first before jumping into piecemeal changes. Feel free to reopen with that.

**Comment by hewillk** [comment]
Yep, but this is a _fix_, see #5519.

**Comment by tkoeppe** [comment]
Oh OK, it was already inconsistent with its own synposis. Sounds good, thanks!

**Comment by tkoeppe** [comment]
@brevzin ^^^ FYI

**Pull request merged**
