### PR TITLE
[containers] Removed redundant specifications of non-member swap

### LINKED ISSUE #1935: [unord] "Specialized algorithms" vs. "Swap"
The original containers use the heading "Specialized algorithms" for the section whose only purpose is to overload `std::swap()`. The unordered containers (which are fairly new) use the heading "Swap". That's inconsistent.

My personal view is that we should remove that subclause entirely:
- The declaration is already shown in the header synopsis.
- The meaning should be established by some front-matter wording in the container requirements, which we already have. Maybe add "equivalent to:" in front of the `a.swap(b)` equivalence in the corresponding table row so that `noexcept` is the same.

### PR DESCRIPTION
**Pull request by jensmaurer**
Fixes #1935.

### CODE REVIEW

**Comment by tkoeppe** [comment]
Please rebase.

@zygoloid: Attention: this change requires announcement.

**Comment by jensmaurer** [comment]
Rebased.

**Comment by jensmaurer** [comment]
Rebased again.

**Comment by jensmaurer** [comment]
... and again.

**Pull request merged**
