### PR TITLE
Fix inconsistencies with hyphens

### PR DESCRIPTION
**Pull request by tocic**
* "cross-reference": [dictionary](https://www.thefreedictionary.com/cross-reference), [repo](https://github.com/cplusplus/draft/search?l=TeX&q=%22cross+references%22), [ngrams](https://books.google.com/ngrams/graph?content=cross+reference%2C%5Bcross+-+reference%5D&year_start=1800&year_end=2019&corpus=en-2019&smoothing=3&case_insensitive=true)
* "multidimensional": [dictionary](https://www.thefreedictionary.com/multidimensional), [repo](https://github.com/cplusplus/draft/search?l=TeX&q=%22multidimensional%22%2C%22multi-dimensional%22), [ngrams](https://books.google.com/ngrams/graph?content=multidimensional%2C%5Bmulti+-+dimensional%5D&year_start=1800&year_end=2019&case_insensitive=on&corpus=en-2019&smoothing=3)
* "well-formed": [dictionary](https://www.thefreedictionary.com/well-formed), [repo](https://github.com/cplusplus/draft/search?q=%22well+formed%22), [ngrams](https://books.google.com/ngrams/graph?content=well+formed%2C%5Bwell+-+formed%5D&year_start=1800&year_end=2019&case_insensitive=on&corpus=en-2019&smoothing=3)
* "well-defined": [dictionary](https://www.thefreedictionary.com/well-defined), [repo](https://github.com/cplusplus/draft/search?l=TeX&q=%22well+defined%22), [ngrams](https://books.google.com/ngrams/graph?content=well+defined%2C%5Bwell+-+defined%5D&year_start=1800&year_end=2019&case_insensitive=on&corpus=en-2019&smoothing=3)
* "error-prone": [dictionary](https://www.thefreedictionary.com/error-prone), [repo](https://github.com/cplusplus/draft/search?l=TeX&q=%22error+prone%22), [ngrams](https://books.google.com/ngrams/graph?content=error+prone%2C%5Berror+-+prone%5D&year_start=1800&year_end=2019&case_insensitive=on&corpus=en-2019&smoothing=3)
* "subdirectory": [dictionary](https://www.thefreedictionary.com/subdirectory), [repo](https://github.com/cplusplus/draft/blob/842424bd228b79876437a1a9393f20f00033476a/source/iostreams.tex#L16485), [ngrams](https://books.google.com/ngrams/graph?content=subdirectory%2C%5Bsub+-+directory%5D&year_start=1800&year_end=2019&case_insensitive=on&corpus=en-2019&smoothing=3)

### CODE REVIEW

**Comment by JohelEGP** [comment]
> multidimensional

That's consistent with `__cpp_multidimensional_subscript`.

**Comment by tocic** [comment]
I've rebased the PR onto the current `main`. No new problems have been found in the commits in between.

**Review by jensmaurer — APPROVED** [review]
This seems to be an improvement.

I'd prefer to structure the commits according to the word being fixed, not according the subclause, though.

**Comment by tocic** [comment]
Do you mean only one commit per word, or just that a commit shouldn't fix multiple words? The former will result in long commit messages, if I need to enumerate all the subclauses. The latter will result in shorter messages, but you still won't be able to review all the changes to one word at a time.

**Comment by JohelEGP** [comment]
For the former, if there are more than 2-3 subclauses, you can use [std] if it spans multiple Clauses, or refer to parent subclauses rather than the specific subclauses. For example, 7cc17d9b5b8417deb01bc21e6cecf78d8c7e2dae can just be [filesystems].

**Comment by tkoeppe** [comment]
Thank you for the very tidy commits!

**Pull request merged**
