### PR TITLE
Remove space after \placeholder so can embed in code.

### PR DESCRIPTION
**Pull request by burblebee**

### CODE REVIEW

**Comment by tkoeppe** [comment]
I see only two diffs in `diffpdf`, and in both cases this PR is an improvement. Example:

image

(The same would exist if one were to move the `placeholder{}` inside the code.)

With the PR:

image

**Comment by zygoloid** [comment]
Are we somehow missing an italic correction after the R? We clearly had too much space beforehand, but it looks like slightly too little now. Anyway, as you say, this is an improvement.

**Comment by burblebee** [comment]
On Wed, Dec 09, 2015 at 05:17:32PM -0800, Richard Smith wrote:
> Are we somehow missing an italic correction after the R? We clearly had too much space beforehand, but it looks like slightly too little now. Anyway, as you say, this is an improvement.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/cplusplus/draft/pull/553#issuecomment-163455625

To be honest, I made this change so long ago, I can't remember why I wanted it - I remember wanting to use it for something but not being able to because of this.. But I only just recently learned how to do "git pull"s for these things, and memory fades.  Doh!

**Comment by tkoeppe** [comment]
@zygoloid: Oddly enough, no permutation of `\nocorr` or `\/` seems to have any effect on this.

It's different if we placed the placeholder inside the code, `\tcode{foo_\placeholder{N}_bar}`, but we're not doing that here.

@burblebee: I think the screenshot I pasted shows why you wanted this -- a good change. And keep the pull requests coming :-)

**Comment by burblebee** [comment]
On Thu, Dec 10, 2015 at 01:49:32AM -0800, Thomas Köppe wrote:
> 
> @burblebee: I think the screenshot I pasted shows why you wanted this -- a good change. And keep the pull requests coming :-)

Yeah, there was a case where I really wanted to use placeholder but couldn't because of the space.  But by the time I got around to fixing placeholder I couldn't remember where that was anymore.  Doh!

**Pull request merged**
