### PR TITLE
[futures.async] Use code font for "std::async"

### PR DESCRIPTION
**Pull request by K-ballo**

### CODE REVIEW

**Comment by sigfpe** [comment]
Why is unqualified `async` an editorial change?-------- Original message --------From: Agustín Bergé <notifications@github.com> Date: 11/21/2015  5:00 PM  (GMT-08:00) To: cplusplus/draft <draft@noreply.github.com> Subject: [draft] [futures.async] Replace "std::async" with "async" in code
  font (#570) 




You can view, comment on, or merge this pull request online at:
  https://github.com/cplusplus/draft/pull/570

Commit Summary

  [futures.async] Replace "std::async" with "async" in code font


File Changes

  
    M
    source/threads.tex
    (2)
  


Patch Links:

  https://github.com/cplusplus/draft/pull/570.patch
  https://github.com/cplusplus/draft/pull/570.diff

**Comment by K-ballo** [comment]
> Why is unqualified `async` an editorial change?

Because of 17.6.1.1 [contents]/3, but even without that simply because it is a note.

**Comment by sigfpe** [comment]
Thanks. Notes aren't normative, but we want to keep them confusion-free.-------- Original message --------From: Agustín Bergé <notifications@github.com> Date: 11/21/2015  6:00 PM  (GMT-08:00) To: cplusplus/draft <draft@noreply.github.com> Cc: sigfpe <sig.fpe@axiomatics.org> Subject: Re: [draft] [futures.async] Replace "std::async" with "async" in code
  font (#570) 

Why is unqualified async an editorial change?


Because of 17.6.1.1 [contents]/3, but even without that simply because it is a note.

**Comment by jwakely** [comment]
Using code font is correct. Normally I would say that the qualification is redundant because of 17.6.1.1, but in this case it does help avoid confusion between the function template `std::async` and the enumerator `std::launch::async` ... _but_ in fact the destructor won't block if the `launch::deferred` policy is chosen, so arguably the note could be changed to refer to `launch::async` not the function template!

But as written, where it refers to the function template, I think disambiguating with the qualification is useful.

**Pull request merged**
