### PR TITLE
[dcl.attr.grammar] Clarify that only non-standard attributes can be ignored CWG2538

### PR DESCRIPTION
**Pull request by jensmaurer**

### CODE REVIEW

**Comment by jensmaurer** [comment]
This likely needs a CWG issue; see http://lists.isocpp.org/ext/2021/12/18597.php

**Comment by AaronBallman** [comment]
I agree that I think this needs a core issue; it has C compatibility concerns and I (personally) don't consider this to be editorial. Thanks for adding it to the CWG agenda!

**Comment by jensmaurer** [comment]
Created CWG2538

**Comment by tkoeppe** [comment]
@jensmaurer What should we do with issues for which you have CWG issues? Keep both open and the latter "fixes" the former?

**Comment by jensmaurer** [comment]
Good question. I think it makes sense to close the editorial issue once we have a core issue; both are publicly visible. Sometimes, the editorial issue contains a bit more (ongoing) discussion than the core issue, though.

**Comment by tkoeppe** [comment]
OK. If it's helpful, we can certainly keep these issues open and then close them all at once.

**Comment by frederick-vs-ja** [comment]
Superseded by #5990?

**Pull request closed without merging**
