### PR TITLE
[std] Avoid hanging paragraphs by introducing "General" subclauses

### LINKED ISSUE #6975: [ISO/CS C++2023] Remove hanging paragraphs
- [x] 7.5 Primary expressions This is a hanging paragraph as per the ISO/IEC Directives Part 2, 22.3.2. Hanging paragraphs" shall be avoided since reference to them is ambiguous.  Please move this text to 7.5 or add another subclause 7.5.1, and renumber the existing subclause levels and cross-references.
- [x] 17.12.5.2 Class coroutine_handle<noop_coroutine_promise> This is a hanging paragraph as per the ISO/IEC Directives, Clause 22.3.3. Please move the text in 17.12.5.2 to 17.12.5.2.1. Otherwise, create another subclause "17.12.5.2.1 General" and relabel the existing ones. 
- [ ] 22.4.4 Class template tuple This is a hanging paragraph as per the ISO/IEC Directives, Clause 22.3.3. Please move the text in 22.4.4 to 22.4.4.1. Otherwise, create another subclause "22.4.4.1 General" and relabel the existing ones. 
- [x] 25.5.2.2 Class template back_insert_iterator this is a hanging paragraph. Either move the content in  25.5.2.2 to 25.2.2.1, or create another subclause directly under 25.5.2.2  "25.2.2.1 General". If a new subclause is added, the existing subclause numbers and cross-references would therefore have to be updated.
- [x] 25.5.2.3 Class template front_insert_iterator this is a hanging paragraph. Either move the content in  25.5.2.3 to 25.2.3.1, or create another subclause directly under 25.5.2.3  "25.2.3.1 General". If a new subclause is added, the existing subclause numbers and cross-references would therefore have to be updated.
- [x] 25.5.2.4 Class template insert_iterator this is a hanging paragraph. Either move the content in  25.5.2.4 to 25.2.4.1, or create another subclause directly under 25.5.2.4  "25.2.4.1 General". If a new subclause is added, the existing subclause numbers and cross-references would therefore have to be updated.
- [x] 30.4.6.4 Class template time_put This is another hanging paragraph - please move the content to 30.4.6.4.1, or add a new subclause directly under it "30.4.6.4.1 General" and rename the existing subclauses
- [x] 30.4.7.2 Class template money_get This is another hanging paragraph - please move the content to 30.4.7.2.1, or add a new subclause directly under it "30.4.7.2.1 General" and relabel the existing subclauses
- [x] 30.4.7.3 Class template money_put this is another hanging paragraph - see the comment above
- [x] 31.5.3 Class template fpos This is another hanging paragraph - please move the content to 31.5.3.1, or add a new subclause directly under it "31.5.3.1 General" and relabel the existing subclauses

### PR DESCRIPTION
**Pull request by jensmaurer**
Fixes ISO/CS comment (C++23 proof)

Fixes #6975

### CODE REVIEW

**Comment by tkoeppe** [comment]
Ahh, so the point of contention are the cases where we have "paragraph-less synopses" only? And I take it that's hard to check automatically?

**Review by tkoeppe — APPROVED** [review]

**Review by jwakely — COMMENTED** [review]
Have we checked whether there are any cross references to the parent which should be adjusted to refer to the new .general subclause?

We've previously broken a large number of refs that way.

**Review by jwakely — APPROVED** [review]
I've checked there are no affected cross-references.

**Comment by tkoeppe** [comment]
Thank you!

**Pull request merged**
