### PR TITLE
[support, diagnostics] Turn synopses into numbered sections

### PR DESCRIPTION
**Pull request by tkoeppe**
This is the first careful approach towards Issue #566. The transformation of `\synopsis` to `rSec2` seems particularly straight-forward in these clauses.

This change introduces the following new stable names (all of which are unique):

**[support]:**

* `new.syn`
* `type.info.syn`
* `exception.syn`
* `support.initlist.syn`

**[diagnostics]:**

* `std.exceptions.syn`
* `syserr.syn`

### CODE REVIEW

**Comment by zygoloid** [comment]
Hmm, what do you think about consistently naming these synopsis sections after the header? (`[stdexcept.syn]`, `[system_error.syn]`, ...).

We're currently inconsistent on this; some are named [surrounding_clause.syn] and some are named [header_name.syn], but in most cases those two names are in fact the same. For instance, we have [time.syn] for <chrono> and [re.syn] for <regex>, and conversely we have [locale.syn] nested within [localization], and [valarray.syn] nested with [numarray]. But naming the synopsis subclauses after their headers seems both more stable and more useful than naming them after the surrounding clause.

**Comment by tkoeppe** [comment]
(Your comment is mis-escaping angled brackets.)

That seems reasonable. I have no strong preference, I was just trying to blend in as much as possible.

I'll rename the stable names.

**Comment by tkoeppe** [comment]
Reworded; new stable names are now:

**[support]:**

* `new.syn`
* `type_info.syn`
* `exception.syn`
* `initializer_list.syn`

**[diagnostics]:**

* `stdexcep.syn`
* `system_error.syn`

**Comment by zygoloid** [comment]
Please rerun `makexref` to regenerate Annex F. Otherwise, this looks good to me.

**Comment by tkoeppe** [comment]
Done.

**Comment by sigfpe** [comment]
Sounds like a great suggestion to me.-------- Original message --------From: Richard Smith <notifications@github.com> Date: 11/23/2015  11:59 AM  (GMT-08:00) To: cplusplus/draft <draft@noreply.github.com> Subject: Re: [draft] [support, diagnostics] Turn synopses into numbered
  sections (#569) 
Hmm, what do you think about consistently naming these synopsis sections after the header? ([stdexcept.syn], [system_error.syn], ...).

We're currently inconsistent on this; some are named [surrounding_clause.syn] and some are named [header_name.syn], but in most cases those two names are in fact the same. For instance, we have [time.syn] for  and [re.syn] for , and conversely we have [locale.syn] nested within [localization], and [valarray.syn] nested with [numarray]. But naming the synopsis subclauses after their headers seems both more stable and more useful than naming them after the surrounding clause.

**Pull request merged**
