### PR TITLE
[ranges.syn] Fix the constraints order of `slide_view`

### PR DESCRIPTION
**Pull request by hewillk**

### CODE REVIEW

**Comment by jensmaurer** [comment]
Why is the other order "better"?

**Comment by hewillk** [comment]
I don't think it's better, I just fixed it with minimal changes.

**Comment by jensmaurer** [comment]
Why is it a "fix"? The end result is two constraints, it seems.

**Comment by hewillk** [comment]
The constraint orders matter, they are different things, you can not
```
namespace std::ranges {
template<view V>
  requires forward_range<V>
class slide_view;

template<forward_range V>
  requires view<V>
class slide_view { };
}
```

**Comment by JohelEGP** [comment]
Because the order is relevant: https://godbolt.org/z/3MPrfeWq6. In this case, the fix orders the constraints like in its class synopsis and those of its iterator/sentinel pair.

**Comment by jensmaurer** [comment]
Ah, ok, this is making the declarations consistent across the synopsis and the iterator/sentinel. Thanks.

**Review by jensmaurer — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Pull request merged**
