### PR TITLE
[utilities] Use code font for named requirements

### PR DESCRIPTION
**Pull request by jlaire**
https://github.com/cplusplus/draft/issues/516

### CODE REVIEW

**Comment by tkoeppe** [comment]
@jwakely: Looks like your area.

**Comment by jlaire** [comment]
`TrivialClock` is similar, and it's always in code font. A global decision about what to do with these would be useful.

**Comment by zygoloid** [comment]
Named sets of requirements are usually formatted in code font. See [utility.requirements] for a bunch of examples, in addition to `TrivialClock`. UnaryTypeTrait, BinaryTypeTrait, and TransformationTrait are outliers here.

I would be fine with having a different typographical convention for them, but it should be applied consistently.

**Comment by jlaire** [comment]
I'll update this PR to change them to code font for consistency tomorrow.

**Comment by jwakely** [comment]
I agree these concept-ish terms should all be typographically distinct, and currently we do that with code font.

I think the one occurrence of "Clock" in code font is wrong, IMHO "Clock requirements" is more like "Associative container requirements" than a concept like "CopyConstructible". (Although it could be argued the other way, `Lockable` and `TimedLockable` are counterexamples.)

As #1154 says, BaseCharacteristic probably shouldn't be one of these terms, so don't change that.

**Comment by jwakely** [comment]
And then there's "Allocator requirements" which is sometimes code font and sometimes not.

**Comment by jlaire** [comment]
I'm not sure if the \defn instances should have \tcode inside them, too.

**Comment by tkoeppe** [comment]
@jwakely: Are you waiting for some changes from the author here?

**Comment by tkoeppe** [comment]
Can you please rebase this? I think we're ready to apply this.

**Comment by jlaire** [comment]
Rebased. "Allocator requirements" and some others are still inconsistent like pointed out by @jwakely, but I don't have time to look into them at the moment. I think they can be done in a separate PR.

**Pull request merged**
