### PR TITLE
[mdspan.mdspan.cons] `OtherIndexType` is not a parameter pack ([mdspan.mdspan.cons]/8.2)

### PR DESCRIPTION
**Pull request by JMazurkiewicz**

### CODE REVIEW

**Review by jwakely — APPROVED** [review]

**Comment by jwakely** [comment]
Even if it were a pack, this would be wrong because it would need to use `is_nothrow_constructible_v` instead.

**Comment by tkoeppe** [comment]
Aren't we missing the `_v` in any case? @jwakely?

**Comment by jwakely** [comment]
Yes indeed - not sure how I missed that despite commenting on it :facepalm:

**Comment by tkoeppe** [comment]
@jwakely PTAL, like so?

**Review by jwakely — APPROVED** [review]

**Pull request merged**
