### PR TITLE
[rand.req.eng] Use \text, not \mbox, in math mode

### LINKED ISSUE #1344: Replace \mbox with \text where appropriate
E.g. in [numerics.tex#L1915](https://github.com/cplusplus/draft/blob/master/source/numerics.tex#L1915)

### PR DESCRIPTION
**Pull request by jensmaurer**
Fixes #1344.

### CODE REVIEW

**Comment by tkoeppe** [comment]
Does this produce a visual difference?

**Comment by jensmaurer** [comment]
No.

**Comment by tkoeppe** [comment]
OK, thanks. For the future, beware that `\text` respects the ambient italicization state (e.g. from `\emph`), so there are situations were you'd prefer `\mathrm` over `\text`. But it's fine here.

**Comment by Eelis** [comment]
Aww, this would've been a perfect opportunity to also fix #1340

**Pull request merged**
