### PR TITLE
Add missing hyphen in 'floating-point'.

### PR DESCRIPTION
**Pull request by Eelis**
For consistency. Addresses #440.

### CODE REVIEW

**Comment by jensmaurer** [comment]
Looks good to me.

**Comment by tkoeppe** [comment]
Does the index need updating, too?

**Comment by Eelis** [comment]
Ah, I would say so, yes. Updated.

**Comment by tkoeppe** [comment]
Thanks, that looks good to me, too. I'll leave it to @zygoloid to make changes to the fundamental C++ types, though.

**Comment by jensmaurer** [comment]
This looks good to me.

**Pull request merged**
