### PR TITLE
[expr.ass] Clarify type of assignment-expression

### LINKED ISSUE #4864: [expr.ass] does not specify the type of the expression (and traditionally misuses "result")

### PR DESCRIPTION
**Pull request by jensmaurer**
Fixes #4864

### CODE REVIEW

**Comment by tkoeppe** [comment]
Could you please add a tiny bit of motivation/background to a second paragraph in the commit message, as discussed in the linked issue? Then feel free to commit. Thanks!

**Comment by jensmaurer** [comment]
@tkoeppe: better?

**Comment by tkoeppe** [comment]
Yes, nice, thanks!

**Comment by languagelawyer** [comment]
So, nobody cares about "result" misuse?

**Pull request merged**
