### PR TITLE
[func.wrap.func] Remove declarations already in [functional.syn]

### PR DESCRIPTION
**Pull request by johelegp**
Partially addresses #4041.

### CODE REVIEW

**Comment by jensmaurer** [comment]
See #4037

**Comment by jensmaurer** [comment]
Editorial meeting: Remove redundancy = apply, but add a cross-reference in functional.syn for swap and operator==.

**Comment by johelegp** [comment]
Could someone reopen this for me, or should I make a new PR? I messed up the initial fixup for the requested changes, but it's fine now: https://github.com/cplusplus/draft/compare/master...johelegp:func.wrap.func.

**Comment by jensmaurer** [comment]
In order to follow the procedure, you need to force-push first, then I can re-open.

**Comment by johelegp** [comment]
I'll do the latter. The branch is already rebased on master, but that's not reflected here.

**Pull request closed without merging**
