### PR TITLE
Add character map and change minimum font size

### PR DESCRIPTION
**Pull request by tkoeppe**
Several improvements here:

* package cmap adds a character map to the PDF to make it searchable.
* <s>package microtype adds micro typography (margin protrusion and microscopic glyph reshaping) which improve looks and increase the quality of justification</s>.
* Lowering the minimum font size from 6pt to 5.5pt allows the `\Cpp` logotype to appear correctly in footnotes. Currently it produces a warning and the pluses are too large.

### CODE REVIEW

**Comment by vermiculus** [comment]
It would be good to squash these commits. :)

**Comment by tkoeppe** [comment]
That's certainly something I can do!

**Comment by zygoloid** [comment]
I've enabled microtype in 4c21b190 to fix issues with guillemet formation for `>>` (see 837fc82b). Thomas, can you remove the addition of microtype here so we don't end up using the package twice?

**Comment by tkoeppe** [comment]
Done!

**Comment by tkoeppe** [comment]
Closing this PR:

* The font size changes have been moved to [PR 579](https://github.com/cplusplus/draft/pull/579).
* The character map is not needed with the lmodern font, which includes its character map. (`cmap` is only needed for the original metafont fonts.)

**Pull request closed without merging**
