### PR TITLE
[mdspan] require conversion results to be nonnegative

### PR DESCRIPTION
**Pull request by CaseyCarter**
"nonnegative" is meaningless for a value of some arbitrary type which we've only required to be convertible to the integral type `index_type`, so this wording clearly intends to constrain the result of the conversion.

### CODE REVIEW

**Comment by CaseyCarter** [comment]
"`meow` is representable as a value of type `T`" also verges on meaningless for an expression `meow` of arbitrary type, but I don't think that can be fixed editorially.

**Comment by CaseyCarter** [comment]
I've pushed two more commits fixing the same issue in a couple more places, with the expectation it will be easiest to review these together. The commits are fine-grained for ease of review and each follow the editorial guidelines so it should be possible to merge them cleanly without squashing.

Shout if I made the wrong call and I should split these up into three PRs.

**Comment by CaseyCarter** [comment]
I should tag @jwakely for review. I know I'm near the boundary of what qualifies as editorial, and _I_ think I'm on the right side of that boundary, but someone more objective should judge whether LWG needs to look at this.

**Review by jwakely — APPROVED** [review]
LGTM. I don't think there's any doubt about what was intended, and this change expresses that more accurately.

**Review by jensmaurer — APPROVED** [review]

**Pull request merged**
