### PR TITLE
[std] Move punctuation to before the footnote marker.

### LINKED ISSUE #4400: Footnote marks should appear after punctuation
If a footnote is meant to attach to a word immediately before a punctuation (full stop, comma, etc.), the footnote mark should appear _after_ the punctuation, for visual spacing reasons.

Bad: `foo bar\begin{footnote} ... \end{footnote}.`

Good: `foo bar.\begin{footnote} ... \end{footnote}`

Action items:
* update the wiki
* fix the few cases that violate this (findable with `git grep`)
* [stretch goal] Add a check.

### PR DESCRIPTION
**Pull request by jensmaurer**
Also add an automated check.

Fixes #4400

### CODE REVIEW

**Comment by tkoeppe** [comment]
Thanks a lot, Jens! Let's wait for the motions to merge, and touch this up if necessary, and then this will go in first thing.

**Comment by jensmaurer** [comment]
Uh, this still needs some fixes for newly-introduced violations caught by check.sh.

**Comment by tkoeppe** [comment]
Thanks, Jens! I'm very glad we're getting this change!

**Comment by jensmaurer** [comment]
Ok, all fixed, ready to merge.

**Pull request merged**
