### PR TITLE
Fix term: template parameter -> argument.

### PR DESCRIPTION
**Pull request by lichray**
I'm sure this sentence is copy-pasted across the "incomplete type" cases...

### CODE REVIEW

**Comment by tkoeppe** [comment]
Do you plan on pursuing this change? @zygoloid: Should this perhaps be a short paper for LWG?

**Comment by tkoeppe** [comment]
@lichray: 1) are you still interested in this PR? 2) the PR is out of sync and needs to be rebased.

**Comment by lichray** [comment]
Rebased.  And I sent a library issue.

**Comment by tkoeppe** [comment]
@lichrayI I wonder, if this is now an LWG issue, and the issue will result in wording changes, then we'd get the change as part of a motion, right? So can we close this PR?

**Comment by lichray** [comment]
I can change the commit message to an application of the motion (if there is one) at that time; I pointed the Proposed resolution of the issue to here actually.

**Comment by tkoeppe** [comment]
@lichray: Hm, I suppose you could do that, but usually motions that come out of meetings will be summarily dealt with after the meeting, so I doubt the editors would at that point look to existing PRs. Consider in particular that there is a limited, short time window post-meeting in which the motions need to be applied, and if the actual motion is different from your current PR, the PR couldn't be used unless you were available for rapid revisions near that time. All told, I imagine that's an unlikely scenario.

**Comment by zygoloid** [comment]
This is filed as wg21.link/lwg2599.

**Pull request closed without merging**
