### PR TITLE
P3508R0 and P3369R0 constexpr for specialized memory algorithms

### LINKED ISSUE #7426: [2024-11 LWG Motion 14] P3508R0 Wording for "constexpr for specialized memory algorithms" and P3369R0 constexpr for uninitialized_default_construct
[P3508R0](https://wiki.edg.com/pub/Wg21wroclaw2024/StrawPolls/p3508r0.html) (Wording for "constexpr for specialized memory algorithms") and [P3369R0](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p3369r0.html) (constexpr for uninitialized_default_construct)

### PR DESCRIPTION
**Pull request by jensmaurer**
Fixes #7426 
Also fixes cplusplus/papers#2026
Also fixes cplusplus/papers#2141

### CODE REVIEW

**Review by jwakely — APPROVED** [review]

**Comment by cpplearner** [comment]
Should this bump `__cpp_lib_constexpr_memory`, following the policy documented in https://wg21.link/sd6#constexpr?

**Comment by jensmaurer** [comment]
__cpp_lib_raw_memory_algorithms is being bumped.  I agree that's odd given SD-6 and the presence of __cpp_lib_constexpr_memory.

**Comment by jwakely** [comment]
Inconsistent application/recollection of the policy

**Comment by jensmaurer** [comment]
Anything we want to do here editorially?  My inclination would be "no", right now.

**Review by tkoeppe — APPROVED** [review]

**Comment by jwakely** [comment]
> Anything we want to do here editorially? My inclination would be "no", right now.

I agree. We can fix it as an LWG issue if needed

**Comment by tkoeppe** [comment]
I'll merge as-is, but we can follow-up if the FT macro needs fixing.

**Pull request merged**
