### PR TITLE
[strings.general,thread.general] Remove nonexistent header and fix some style error

### PR DESCRIPTION
**Pull request by Mick235711**
[strings.general]: Add `<string>` to the String classes subclause
[thread.general]: Remove nonexistent header `<atomic_ref>` and add a comma.

### CODE REVIEW

**Review by jwakely — APPROVED** [review]

**Review by jensmaurer — CHANGES_REQUESTED** [review]
These are two entirely different situations. Please split into two commits.

**Comment by Mick235711** [comment]
> These are two entirely different situations. Please split into two commits.

Done.

**Comment by jensmaurer** [comment]
In the commit description, I'm not seeing what "and fix some style error" would refer to for the second commit. It now exclusively removes a non-existing header from the intro table.

**Comment by Mick235711** [comment]
> In the commit description, I'm not seeing what "and fix some style error" would refer to for the second commit. It now exclusively removes a non-existing header from the intro table.

That part of the message is for adding a comma. The rendered draft looks like
image
And that row is already missing comma as separator. So that commit, in addition to remove the header, also fix this style error.

**Review by jensmaurer — APPROVED** [review]

**Comment by tkoeppe** [comment]
I'll take this and fix up the commit messages -- thank you!

**Pull request closed without merging**
