### PR TITLE
[streambuf.virt.get] use half-open ranges in underflow effects

### PR DESCRIPTION
**Pull request by jwakely**
underflow1
underflow2

We should discuss this before merging, I'm ambivalent about it.

### CODE REVIEW

**Comment by jensmaurer** [comment]
Oh well. This seems to be a presentational improvement. Is that the only place in streambufs where we have that style of description? I wouldn't want to address only one of possibly N adjacent places.
[I still find this "backup sequence" stuff totally obtuse, but that's a different story.]

**Comment by zygoloid** [comment]
I like it. Looks good to merge once @tkoeppe's comment is addressed.

**Comment by jwakely** [comment]
Rebased and added the comma.

**Comment by jwakely** [comment]
I should probably also look at `overflow` in [streambuf.virt.put] which uses a similar style:

> the the `pptr() - pbase()` characters beginning at `pbase()`

**Comment by tkoeppe** [comment]
@jwakely: Yes, sounds good. We don't come past this section very often, so getting all the cleanup done in one go seems like a good idea

**Comment by zygoloid** [comment]
Taking this part for C++17; I'd rather get this in than wait for more cleanups to be added to it.

**Pull request merged**
