### PR TITLE
Escape spaces following mid-sentence periods.

### LINKED ISSUE #2555: [atomics.types.operations]/20 Awkward "E.g." at start of sentence
Consider the "E.g. " below:
image
Some thoughts:
- The space between "E.g." and "list" seems a bit wide, is it possible LaTeX is generating a sentence-space? Should maybe "\ " be used? (Or maybe even "~", to prevent a line break.)
- In the vast majority of cases, the document actually has a comma after "e.g.". Maybe that's the way to go here, too?
- Starting a sentence with the "e.g." abbreviation could be considered poor style to begin with. Maybe nicer to just say "For example,"

### PR DESCRIPTION
**Pull request by Eelis**
Fixes #2555.

### CODE REVIEW

**Comment by tkoeppe** [comment]
Could you attach a diffshot, or at least a representative subset?

**Comment by tkoeppe** [comment]
That is odd! I imagine there may be built-in heuristics that detect things like initials and common abbreviations.

Could you please reduce the change to the minimal effective set? (And do feel free to also remove existing, ineffective backslashes.) Thanks!

**Comment by Eelis** [comment]
For names with initials, how would you feel about using "~", as in "P.J.~Plauger"? We currently don't happen to have a line break there, but if preceding content is changed one day, that could change without us noticing, and might look bad.

**Comment by tkoeppe** [comment]
I feel pretty much entirely indifferent. It's not currently a problem, we don't have a ton of names with initials, nor do we expect to gain more, and the existing occurrences aren't likely to be touched. So I'd just keep it as is, and simple.

Is there a visual diff if you use `~`?

**Comment by godbyk** [comment]
There is no visual difference between using `~` and `\ ` aside from `~` inserting a non-breaking space.

The basic algorithm is that if the character preceding a period is uppercase, then interword spacing is used. Otherwise, end-of-sentence spacing it used.

So `P.J. Plauger` would result in an interword spacing while `E.g. list` would result in end-of-sentence spacing.

**Comment by godbyk** [comment]
Oh, and if you use a comma after `e.g.` and `i.e.` then an interword space will be used there as well.

**Comment by tkoeppe** [comment]
Ah yes, makes sense, thanks.

I would retain the status quo in that case.

**Comment by Eelis** [comment]
Ah great, thanks for the explanation! I'll implement that "character preceding period is uppercase" heuristic for sentence splitting in cxxdraft-htmlgen as well.

That will resolve my real issue (because my ulterior motive was to use the "\ " or "~" to have cxxdraft-htmlgen not split the sentences there), and given that LaTeX apparently already handles almost all of this just fine by itself after all, I agree it's not worth caring about. :)

Closing, cheers!

**Comment by tkoeppe** [comment]
I mean, do feel free to fix that one "E.g." case if you like. Or better yet, say "For example,". Or don't.

**Comment by godbyk** [comment]
Personally, I'd prefer `For example,` as I don't like using `E.g.` or `I.e.` to start a sentence.

**Comment by Eelis** [comment]
Ok you convinced me... but then I discovered that if you force push to a branch used in a pull request that is currently closed, then you cannot reopen that pull request anymore (the "Reopen and comment" button is greyed out now). :)

**Comment by tkoeppe** [comment]
Hah, how weird.

**Comment by johelegp** [comment]
> Ok you convinced me... but then I discovered that if you force push to a branch used in a pull request that is currently closed, then you cannot reopen that pull request anymore (the "Reopen and comment" button is greyed out now). :)

That's solved by force-pushing back to the commit of the PR.

**Pull request closed without merging**
