### PR TITLE
Replace \nonterminal with \grammarterm or \cvqual, as appropriate.

### LINKED ISSUE #1312: Replace \nonterminal with \grammarterm or \cv or \cvqual or ...
... and remove the macro afterwards, taking care of the use(s) in macros.tex itself.

\nonterminal in running text should be \grammarterm these days.

### PR DESCRIPTION
**Pull request by jensmaurer**
Fixes #1312.

### CODE REVIEW

**Comment by tkoeppe** [comment]
Can you run diffpdf?

**Comment by jensmaurer** [comment]
Yes. There are 14 pages with differences, all of them due to the fact that \nonterminal uses a slightly smaller font than \grammarterm or \cvqual.

**Comment by jensmaurer** [comment]
(I've rebased the patch.)

**Comment by tkoeppe** [comment]
Oh, very good, we should fix that. Thanks!

**Pull request merged**
