### PR TITLE
[expr] Add subclauses.

### PR DESCRIPTION
**Pull request by jensmaurer**

### CODE REVIEW

**Comment by zygoloid** [comment]
This introduces an overfull hbox, can you investigate please?

**Comment by jensmaurer** [comment]
This also needs more work to update the cross references that used to point to [expr].

**Comment by jensmaurer** [comment]
Uh, the overfull hbox is hard to fix. Not much wiggle room in horizontal spacing there.

**Comment by jensmaurer** [comment]
Overfull hbox avoided by introducing a bulleted sub-list.

**Pull request merged**
