### PR TITLE
Consistently use 'this International Standard'.

### PR DESCRIPTION
**Pull request by Eelis**
For consistency with all other occurrences.

A related question is whether all occurrences of "this Standard" should really say "this International Standard". (IMHO saying the latter over and over sounds pointless and pompous, but if it's to satisfy some legal requirement, perhaps we ought to do it consistently.)

### CODE REVIEW

**Comment by jensmaurer** [comment]
Yes, we want to say "this International Standard". Always. (We're not mentioning it too often, so it's ok to be formally correct in all cases.)

**Comment by tkoeppe** [comment]
Either seems fine ("this Standard" or "this International Standard"); you guys figure out which one you want, and leave a message when it's ready.

**Comment by Eelis** [comment]
I'll update the patch to make it long form everywhere :)

**Comment by jensmaurer** [comment]
The
[ISO Directives Part 2](http://www.iec.ch/members_experts/refdocs/iec/isoiecdir-2%7Bed7.0%7Den.pdf), section 3.1.4, say that "International Standard" refers to a standard issued by ISO or IEC, as opposed to any random standard. That, to me, is a clear indication we should not use simply "standard", which has a broader definition.

**Comment by Eelis** [comment]
@jensmaurer Cool, thanks for looking it up! Patch amended.

**Comment by jensmaurer** [comment]
Looks good to me.

Leaving a message for @tkoeppe, as requested.

**Comment by tkoeppe** [comment]
Thanks. @jensmaurer, would you mind adding a note to the wiki about this so we remember in the future?

**Comment by jensmaurer** [comment]
@tkoeppe: Done.

**Comment by timsong-cpp** [comment]
@CaseyCarter yesterday pointed to ISO/IEC directives part 2 §10.6 "References in a document to itself" regarding [a similar issue I reported for the Ranges TS](https://github.com/ericniebler/stl2/pull/304):

> For an individual document, the form "this document" shall be used.

This is a change from the sixth edition and explicitly called out in the foreword of the seventh edition of the directives.

**Comment by Eelis** [comment]
@timsong-cpp Ah damn, I wish you'd been here half an hour earlier :)

**Comment by tkoeppe** [comment]
Well, it's still an improvement over the status quo ante, and presumably we'd never even have heard of this discrepancy if it hadn't been for this PR.

**Pull request merged**
