### PR TITLE
[range.as.rvalue.view] Fix curly brace format

### PR DESCRIPTION
**Pull request by hewillk**
Should this be detected?

### CODE REVIEW

**Comment by tkoeppe** [comment]
Before we do all these one by one, could you maybe have a look at the clause as a whole to see if there are other style violations like this?

> Should this be detected?

Can you describe such a check in a way we can run in the check script?

**Comment by hewillk** [comment]
OK, I'll check them one by one.

> Can you describe such a check in a way we can run in the check script?

This might take some thought.

**Comment by hewillk** [comment]
Also fixed inconsistent constraint ordering with synopsis.

**Comment by tkoeppe** [comment]
@brevzin Could you please take a look?

**Comment by brevzin** [comment]
So this swaps the two constraints to be consistent with the synopsis (oops) and moves the open brace to the start of the previous line? Looks good.

**Comment by tkoeppe** [comment]
@brevzin Great, thanks! Yes, I wanted to check that that was indeed an error in the paper, and that this fix is correct.

**Pull request merged**
