### PR TITLE
[std] Use consistent margins for codeblocks.

### LINKED ISSUE #3186: [everywhere] Use consistent margins for codeblocks
Compare:

https://github.com/cplusplus/draft/blob/deb086c434dcaf864221f51e887477c0842aad2b/source/classes.tex#L221-L222

https://github.com/cplusplus/draft/blob/deb086c434dcaf864221f51e887477c0842aad2b/source/classes.tex#L249-L250

This difference is visible in the PDF:

image

### PR DESCRIPTION
**Pull request by Eelis**
Fixes #3186.

### CODE REVIEW

**Comment by tkoeppe** [comment]
I think this is good, but would like @zygoloid to confirm that this isn't undoing some of the "deliberate diversity of core style".

**Comment by jensmaurer** [comment]
I certainly hope that random full-codeblock indentation isn't part of the "core diversity".

**Comment by godbyk** [comment]
If you wish to keep the indentation in the LaTeX source code but have it removed in the PDF output, you can add <tt>gobble=<i>n</i></tt> to [`\lstset`](https://github.com/cplusplus/draft/blob/master/source/macros.tex#L410) (where _`n`_ is the number of characters to outdent the code block).

**Comment by jensmaurer** [comment]
Thanks, @godbyk. Though I doubt we want to allow inconsistent codeblock indentation across the LaTeX source to start with.

**Pull request merged**
