### PR TITLE
Fix typo and bad formatting

### PR DESCRIPTION
**Pull request by jfbastien**
In the spirit of https://github.com/WebAssembly/spec/pull/276

### CODE REVIEW

**Comment by tkoeppe** [comment]
Please amend the commit message to follow our standard commit message conventions.

**Comment by W-E-Brown** [comment]
I strongly object to this proposed change; it subverts the point of the existing wording (which has been in place in working drafts for 20 years or so).  Surely there are far more important details to worry about.

**Comment by jwakely** [comment]
Nope.

**Comment by jwakely** [comment]
(But thanks for the chuckle!)

**Pull request closed without merging**
