### PR TITLE
[ranges] Indexing fixes for iterator and sentinel classes

### LINKED ISSUE #5832: Some exposition-only types are not formatted as such in the index
See `chunk_view`'s _inner-iterator_ and _outer-iterator_ and _sentinel_:

image

And adjacent_transform_view and adjacent_view's _iterator_ and _sentinel_:

image

And the index entries for their `base()` member of various iterator and sentinel types:

image
image

And so on ...

image

image

image

image

image

### PR DESCRIPTION
**Pull request by jensmaurer**
Also add automated checks.

Fixes #5832

### CODE REVIEW

**Comment by tkoeppe** [comment]
The collation seems to go wrong. Maybe we need to remove the markup from the sort order somehow?

**Comment by jensmaurer** [comment]
Oh well.

**Comment by jensmaurer** [comment]
@tkoeppe , do you have a specific example? It doesn't seem to matter in the cases I looked at (e.g. elements_view::iterator / sentinel).

**Comment by tkoeppe** [comment]
I think this is a pre-existing problem, indeed. Let me take a quick look.

**Comment by tkoeppe** [comment]
Hm, this requires a separate fix, so it's unrelated to this patch.

**Pull request merged**
