### PR TITLE
[basic.fundamental] Excise normative requirements on std::numeric_limits

### PR DESCRIPTION
**Pull request by jensmaurer**

### CODE REVIEW

**Comment by jensmaurer** [comment]
On CWG's agenda: https://wiki.edg.com/bin/view/Wg21telecons2021/CoreWorkingGroup

**Comment by jensmaurer** [comment]
Approved by CWG 2021-11-12.

**Comment by jensmaurer** [comment]
@tkoeppe, this was approved by CWG. Any final thoughts before merging?

**Comment by tkoeppe** [comment]
Looks good, go for it! Thanks!

**Review by jwakely — APPROVED** [review]

**Pull request merged**
