### PR TITLE
[enum.copy_options] Rephrase restriction on copy_options values.

### LINKED ISSUE #1422: [enum.copy_options] Poor wording for requirement on elements set in copy_options
[enum.copy_options] says:

> Calling a library function with more than a single constant for an option group results in undefined behavior. 

I don't like how this is phrased. Firstly, which library? Does it apply to _any_ function in the standard library, e.g. `std::move`?

Secondly, I'd prefer if it used the term of art "is set" for bitmask elements set in a bitmask object.

This doesn't exactly roll off the tongue, but I think it's more precise:

"A value of type `copy_options` that is passed to a function described in subclause 27.10 shall have at most one element set from each option group."

### PR DESCRIPTION
**Pull request by jensmaurer**
Fixes #1422.

### CODE REVIEW

**Comment by jensmaurer** [comment]
As discovered in #1422, it turns out that the requirements are already spelled out with the two function families that use copy_options. My new patch simply removes the general requirement and slightly adjusts the requires clauses with the individual functions.

**Comment by jensmaurer** [comment]
@jwakely: What do you think?

**Comment by timsong-cpp** [comment]
Hmm, one is "from each `copy_options` option group", the other is simply "from each option group". Might make them consistent as a drive-by fix.

**Comment by jensmaurer** [comment]
Rebased.

**Comment by jwakely** [comment]
Looks good to me.

**Comment by jensmaurer** [comment]
Now also addressing @timsong-cpp's comment.

**Pull request merged**
