### PR TITLE
[basic.scope.class] Use a regular itemize environment instead of enumeraten

### PR DESCRIPTION
**Pull request by Eelis**
diffs

### CODE REVIEW

**Comment by tkoeppe** [comment]
@zygoloid: Your favourite language concept -- care to review this?

**Comment by sigfpe** [comment]
Why?
-------- Original message --------From: Eelis <notifications@github.com> Date: 11/23/16  2:43 AM  (GMT-08:00) To: cplusplus/draft <draft@noreply.github.com> Subject: [cplusplus/draft] [basic.scope.class] Use a regular itemize
  environment instead of enumeraten (#1102) 




You can view, comment on, or merge this pull request online at:
  https://github.com/cplusplus/draft/pull/1102

Commit Summary

  [basic.scope.class] Use a regular itemize environment instead of enumeraten.


File Changes

  
    M
    source/basic.tex
    (4)
  


Patch Links:

  https://github.com/cplusplus/draft/pull/1102.patch
  https://github.com/cplusplus/draft/pull/1102.diff


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cplusplus/draft","title":"cplusplus/draft","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cplusplus/draft"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"[basic.scope.class] Use a regular itemize environment instead of enumeraten (#1102)"}],"action":{"name":"View Pull Request","url":"https://github.com/cplusplus/draft/pull/1102"}}}

**Comment by Eelis** [comment]
Oh, I just noticed that all other lists use the styling with "(x.y)" numbers in the margin. If there's a subtle reason for this list to be an anomaly, please close, and in that case my apologies for the noise. :)

**Comment by sigfpe** [comment]
Why special-case this paragraph?
-------- Original message --------From: Thomas Köppe <notifications@github.com> Date: 11/23/16  2:44 AM  (GMT-08:00) To: cplusplus/draft <draft@noreply.github.com> Subject: Re: [cplusplus/draft] [basic.scope.class] Use a regular itemize
  environment instead of enumeraten (#1102) 
@zygoloid: Your favourite language concept -- care to review this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cplusplus/draft","title":"cplusplus/draft","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cplusplus/draft"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tkoeppe in #1102: @zygoloid: Your favourite language concept -- care to review this?"}],"action":{"name":"View Pull Request","url":"https://github.com/cplusplus/draft/pull/1102#issuecomment-262481762"}}}

**Comment by Eelis** [comment]
@sigfpe Are you aware that your replies are creating rather spammy-looking comments in the github thread at https://github.com/cplusplus/draft/pull/1102 ?

**Comment by jwakely** [comment]
That's the point. Currently it's a special case, the change makes it consistent  with the rest of the standard.

**Comment by tkoeppe** [comment]
I'm generally in favour of having fewer different stylistic elements, and this generally looks like the right direction.  Ordered lists are very rare and should only be used when something really needs to be done in order (e.g. translation phases).

**Comment by jwakely** [comment]
The spammy-looking comments come from replying by email rather than on the website. I've edited them to remove the noise.

**Comment by Eelis** [comment]
Ah I see, cheers!

**Comment by tkoeppe** [comment]
@Eelis: Can you take a look at the other `\enumeraten` in iostreams? Maybe we can kill that environment with fire.

**Comment by sigfpe** [comment]
I am not sure I follow.  The (x.y) style was introduced so that we can tell that bullet y is within paragraph x, when referenced. Why is this in the "right sirection"?

**Comment by tkoeppe** [comment]
@sigfpe: There's nothing inherently ordered about the items in question, so a regular list seems like the natural choice here. The "right direction" is to remove stylistic deviations like this.

It might be interesting to trace the origin of this section; does anyone have the ARM at hand?

**Comment by Eelis** [comment]
Hmm, I just noticed that the only difference between "enumeraten" and "enumerate" is that the former uses "1)" while the latter uses "1." for the item number.

So perhaps a less controversial path forward is to first replace all "enumeraten" with "enumerate" (a minimal stylistic change). Then, we can separately decide which "enumerate" occurrences should become "itemize" (a semantic change).

**Comment by sigfpe** [comment]
If there is nothing inherently ordered, why would an enumeration be the "right direction" then?
Chapter 3 of the ARM didn't bother with this; but I am not sure we need to go back that far.

**Comment by tkoeppe** [comment]
@sigfpe: I don't understand - nobody is proposing an enumeration. We're proposing *removing* an enumeration and replacing it with an itemization.

**Comment by tkoeppe** [comment]
@Eelis: yes, perhaps that'd be a start. Enumerations are so rare that we should probably not need to have more than one stylistic component for them.

**Comment by sigfpe** [comment]
Replying to my own comment earlier regarding ARM: the C++98 version had the current form instead of unnumbered itemized list.

**Comment by Eelis** [comment]
Now that #1105 was merged, we can start to consider more generally which enumerations should be replaced with itemizations, but this pull request is not the best place for that. Closing.

**Comment by tkoeppe** [comment]
@Eelis: We could still try to get rid of `enumeratea`. If you like, maybe have a look at numerics.tex.

**Pull request closed without merging**
