### PR TITLE
Qualify move & forward with std::

### PR DESCRIPTION
**Pull request by lichray**
Please check PDF output to ensure that the table is not messed up.

### CODE REVIEW

**Comment by tkoeppe** [comment]
Could you please add the section or file reference to the commit message? Take a look how other commits are labelled.

**Comment by lichray** [comment]
The changes happen to be in one file but actually this change is applied globally.  The title matches the intention.

**Comment by jwakely** [comment]
Thanks, applied partially as 4d69bcb2f0c8fea313fdc653c01e2f736525b976

Qualifying `std::forward` isn't necessary because the template argument list prevents ADL (although I always get confused by the specifics of that rule).

**Comment by timsong-cpp** [comment]
> because the template argument list prevents ADL

It doesn't. ADL takes place as normal for `meow<T>(stuff)`, as long as ordinary unqualified lookup finds a function template named `meow` in scope so that the compiler knows how to parse the `<`.

**Pull request closed without merging**
