### PR TITLE
[expr.prim.req.nested] Fix restriction on local parameters CWG2517

### PR DESCRIPTION
**Pull request by jensmaurer**
Partially addresses #4830

This was discussed in #4832

### CODE REVIEW

**Comment by BRevzin** [comment]
Does this paragraph serve a purpose? @zygoloid asked that [here](https://lists.isocpp.org/core/2019/06/6579.php) and the only response was that it's indeed useless. Isn't the check on `requires a == 0;` already rejected by [\[expr.const\]/5.9](http://eel.is/c++draft/expr.const#5.9)?

This also seems like a case that [P2280](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2280r3.html) ought to address, making something like this valid:

```cpp
struct A {
    constexpr int size() const { return 42; }
};

template <class T>
concept C = requires (T t) {
    requires t.size() > 10; 
};

static_assert(C<A>);  // only clang rejects, explicitly citing this rule
static_assert(C<A&>); // everyone rejects, but P2280 would presumably allow 
```

**Comment by jensmaurer** [comment]
> Isn't the check on requires a == 0; already rejected by [expr.const]/5.9?

Good point. This seems to be missing a core issue.

**Comment by jensmaurer** [comment]
CWG2517

**Comment by frederick-vs-ja** [comment]
Should have been superseded by #6118 (https://github.com/cplusplus/draft/pull/6118/commits/7a947d7b2d374bdb2e59083918a24f219d64641e).

**Pull request closed without merging**
