### PR TITLE
[re] Remove whitespace before \colcol.

### PR DESCRIPTION
**Pull request by cpplearner**

### CODE REVIEW

**Comment by jensmaurer** [comment]
Wait. We usually use "::", but sometimes we use \colcol, for no apparent reason.

So, I'd much prefer to globally replace \colcol with :: (and remove the whitespace in that process) instead of just removing whitespace, but leaving \colcol in.

**Comment by jensmaurer** [comment]
The patch as proposed looks good to me.

**Comment by tkoeppe** [comment]
This seems like churn. I'd say if you want to make progress here, replace the `\colcol` with plain double colons while you're at it.

**Comment by tkoeppe** [comment]
Looks good, thanks. Can you just check quickly that this doesn't introduce any paragraph composition problems (overlong lines)? (E.g. by comparing the output of `fgrep std.log -e Overfull -e .tex` before and after.)

**Comment by cpplearner** [comment]
No. The output is the same before and after.

**Comment by tkoeppe** [comment]
Thanks!

**Pull request merged**
