### PR TITLE
[temp.variadic] Clarify template parameter packs not introduced by pa…

### PR DESCRIPTION
**Pull request by jensmaurer**
…ck expansions.

Fixes #4707

### CODE REVIEW

**Comment by xmh0511** [comment]
Thanks. The section [temp.variadic] will be great clear.

**Comment by tkoeppe** [comment]
@zygoloid: could you please take a look?

**Review by zygoloid — APPROVED** [review]
Looks like an improvement to me.

**Comment by tkoeppe** [comment]
Thanks! Merging.

**Pull request merged**
