### PR TITLE
[LWG motion 10] P2542R8 views::concat

### LINKED ISSUE #6881: [2024-03 LWG Motion 10] views::concat
https://wiki.edg.com/pub/Wg21tokyo2024/StrawPolls/P2542R8.html

### PR DESCRIPTION
**Pull request by burblebee**
Fixes #6881.
Fixes cplusplus/papers#1204

### CODE REVIEW

**Comment by burblebee** [comment]
The build is failing with the following errors due to workarounds for Overfull issues:
```
Run ../tools/check-output.sh
::error concept bidirectional has no definition
::error concept concat-is-bidirec\-tional has no definition
::error concept concat-is-ran\-dom-access has no definition
::error concept cess has no definition
Error: Process completed with exit code 1.
```

The offending bits of source are:
```
\exposconcept{concat-is--\linebreak{}bidirectional}<Const, Views...>}
\exposconcept{concat-is-bidirec\-tional}
\exposconcept{concat-is-ran\-dom-access}
\exposconcept{concat-is-random-ac-\linebreak{}cess}<Const, Views...>}
```

Any ideas for how to make the build happy?

**Comment by jensmaurer** [comment]
Use `\exposconceptx` .   See macros.tex

**Comment by burblebee** [comment]
> Use `\exposconceptx` . See macros.tex

Thank you!

**Comment by jensmaurer** [comment]
Hm... I can reproduce those errors. Looks like the .ind format changed a little.  But why does this appear with exactly this pull request, and none of the others?

**Comment by jensmaurer** [comment]
You're using \exposconceptx incorrectly.  It has two parameters, not just one.  Example:

\exposconceptx{concat-is-ran\-dom-access}{concat-is-random-access}

Please fix.

**Comment by burblebee** [comment]
> You're using \exposconceptx incorrectly. It has two parameters, not just one. Example:

Ah! Thank you! fixed and pushed.

**Comment by tkoeppe** [comment]
Thank you very much!

**Pull request merged**
