### PR TITLE
Replace [fig:iostreams.streampos] with words

### PR DESCRIPTION
**Pull request by jwakely**
This supersedes #4298 as it includes that commit, and another one to replace the information in the figure with prose, as I suggested in #4246.

I've also restored the mention of `ssize_t` and reworded the second footnote in [stream.types], to address my comment at https://github.com/cplusplus/draft/pull/1986#discussion_r507630555

### CODE REVIEW

**Comment by tkoeppe** [comment]
@jwakely: could you please rebase this?

**Comment by jwakely** [comment]
Rebased.

**Comment by tkoeppe** [comment]
@jwakely: I moved the new note into the commit that deletes the figure; PTAL?

**Review by jwakely — COMMENTED** [review]
LGTM

**Pull request merged**
