### PR TITLE
[expr.add] Use better example

### PR DESCRIPTION
**Pull request by languagelawyer**
Related to #3614

### CODE REVIEW

**Comment by tkoeppe** [comment]
Has the discussion in the linked issue been resolved?

@jensmaurer: any thoughts on this?

**Comment by jensmaurer** [comment]
I think the main gist here is that using a pointer-to-base when actually pointing to a derived class is fine in most cases, but not in the array indexing case. Changing the example as suggested is losing that point.

**Comment by languagelawyer** [comment]
> I think the main gist here is that using a pointer-to-base when actually pointing to a derived class is fine in most cases, but not in the array indexing case.

It is UB in most (if not all) cases (member access, member function call etc.).

Using pointer-to-base which points to base subobject is fine in all cases (even in the array indexing case). What you can violate with such a pointer, is [expr.add]/4, not [expr.add]/6.

**Comment by tkoeppe** [comment]
@jensmaurer I'm not sure what to do here. Should we move this example to p4 and edit the example in p6 like proposed? Or just keep the status quo?

**Comment by jensmaurer** [comment]
I like the int / unsigned int example in p6, because it is mildly surprising.

I also like to retain the base / derived situation, but maybe it's worthwhile to formulate that in terms of "base class subobject" in p4, as a special case for when the p4.2 precondition isn't satisfied.

**Comment by tkoeppe** [comment]
@languagelawyer Could you take another stab at this then?

**Comment by languagelawyer** [comment]
@jensmaurer not sure what you meant, but I did this. Note, the Note is outside the `itemize` environment, unlike in the next paragraph.

**Comment by tkoeppe** [comment]
@jensmaurer Could you please take another look here?

**Review by jensmaurer — COMMENTED** [review]
That looks reasonable to me.

If you can get @zygoloid  to okay these changes, we can apply them right away, otherwise I'd like to have CWG assent.

**Comment by tkoeppe** [comment]
@languagelawyer could you please have a look?

**Pull request merged**
