### PR TITLE
[std] Remove unnecessary bracketing in \tcode and retire \dcr

### LINKED ISSUE #4097: [libraryindex] Harmonize index entries for operator--
There are currently 3 separate (top-level) index entries for `operator--` in the "Index of library names". This is because there are three conventions in use for the index keys:

https://github.com/cplusplus/draft/blob/e224430986ce8800de375ee975e0d89a64365fc7/source/time.tex#L1404

https://github.com/cplusplus/draft/blob/e224430986ce8800de375ee975e0d89a64365fc7/source/iterators.tex#L5409

https://github.com/cplusplus/draft/blob/e224430986ce8800de375ee975e0d89a64365fc7/source/time.tex#L2303

### PR DESCRIPTION
**Pull request by Eelis**
Together, these two changes fix #4097.

No visible difference outside of the index.

### CODE REVIEW

**Comment by jensmaurer** [comment]
@Eelis , please rebase, resolve the conflict, and force-push.

**Comment by Eelis** [comment]
Rebased.

**Comment by zygoloid** [comment]
Sorry for not merging sooner, needs another rebase now.

**Review by zygoloid — APPROVED** [review]

**Comment by Eelis** [comment]
Rebased.

**Pull request merged**
