### PR TITLE
[obj.lifetime] Use static_cast instead of C-style cast expression

### PR DESCRIPTION
**Pull request by blackteahamburger**

### CODE REVIEW

**Comment by Dani-Hub** [comment]
This doesn't work, because this wording is supposed to be valid for pointers to cv-char as well, and the static_cast cannot do this.

**Comment by blackteahamburger** [comment]
> This doesn't work, because this wording is supposed to be valid for pointers to cv-char as well, and the static_cast cannot do this.

Done.

**Comment by tkoeppe** [comment]
@jwakely could you please take a look?

**Comment by tkoeppe** [comment]
Thanks! So is even the status quo questionable then? Should I file an issue?

**Comment by jwakely** [comment]
Yes please.

**Comment by tkoeppe** [comment]
Done. This is now being handled as an LWG issue.

**Pull request closed without merging**
