### PR TITLE
[dcl.pre] Reorder paragraphs

### LINKED ISSUE #338: [dcl.pre] paragraphs are in a strange order
First we have "the simple-declaration <blah> is divided into three parts".
Then a digression on attribute-declarations and scopes.
Then back to simple-declarations again.
Then a digression on static_assert-declarations and empty-declarations.
Then, with no introduction or explanation, some words about init-declarators, and about decl-specifier-seq's. That's clearly supposed to be related to the prior stuff about simple-declarations, but we're too far away for that to be a reasonable implied context.
Oh, then a lie: "Syntactic components beyond those found in the general form of declaration are added to a function declaration to make a function-definition." This means to say "beyond those found in the general form of a simple-declaration"; a function-definition is one of the possibilities in the general form of "declaration".
And then back to decl-specifier-seq's again.

This is a mess and should be fixed.

Related: we should check which of these simple-declaration rules should also apply to function-definitions and member-declarations, and suggest to core that any discrepancies be fixed.

### PR DESCRIPTION
**Pull request by jensmaurer**
Group discussion of simple-declaration and
move other kinds of declarations to the end.

Fixes #338

### CODE REVIEW

**Comment by tkoeppe** [comment]
This looks good, but maybe @opensdh could lend a second pair of eyes?

**Review by opensdh — APPROVED** [review]
I might move the scope discussion up rather than down (in case now or in the future there is some text in [dcl.pre] that depends on its "utterances" rule), but other than that this looks thoroughly benign.

**Comment by tkoeppe** [comment]
@jensmaurer: feel free to merge this, with or without @opensdh's minor suggestion!

**Comment by tkoeppe** [comment]
@opensdh: Thank you very much!

**Comment by jensmaurer** [comment]
Moved "utterances" up a little.

**Pull request merged**
