### PR TITLE
[expr.static.cast]

### PR DESCRIPTION
**Pull request by horribleCCguru**
grammatical error.

### CODE REVIEW

**Comment by JohelEGP** [comment]
Resolves #6261.
I suggest you review <https://github.com/cplusplus/draft/wiki/Commit-message-format>.

**Comment by horribleCCguru** [comment]
Resolves https://github.com/cplusplus/draft/issues/6261

**Comment by horribleCCguru** [comment]
@JohelEGP cala boca manito

**Comment by jwakely** [comment]
Please behave respectfully, or don't contribute to this repository.

**Comment by horribleCCguru** [comment]
yes, i was out of line here, and felt it was a backhand when I read it. Apologies <3 love for everyone

**Pull request closed without merging**
