### PR TITLE
[over.match.copy] Clarify candidate function selection for references.

### LINKED ISSUE #2053: [over.match.copy]: "return lvalues or xvalues" makes me uncomfortable
**UPD**:  [over.match.copy] and [over.match.conv]

The sections [over.match.copy] and [over.match.conv] have statements like: "Conversion functions that return “reference to X” return lvalues or xvalues ..."

[diff.expr]/4 is also broken: "C++ is an object-oriented language, placing relatively more emphasis on lvalues. For example, functions may return lvalues."

"return _value category_" sounds illiterate for me.

Proposed wording:

```
The result of calling a
conversion function that returns ``reference to
\tcode{X}''
is
lvalue or xvalue, depending on the type of reference, of type
\tcode{X}
and is therefore considered to yield
\tcode{X}
for this
process of selecting candidate functions.
```

### PR DESCRIPTION
**Pull request by jensmaurer**
Fixes #2053.

### CODE REVIEW

**Comment by languagelawyer** [comment]
[over.match.conv] also needs the fix!

**Comment by zygoloid** [comment]
I agree, we should update [over.match.conv] too (though I'm not sure what needs changes in [diff.expr]/4?). I also think it would be reasonable to convert the wording in question to a note.

**Comment by languagelawyer** [comment]
> though I'm not sure what needs changes in [diff.expr]/4

I've cited in #2053:
> C++ is an object-oriented language, placing relatively more emphasis on lvalues.
[For example, **functions may return lvalues**.](http://eel.is/c++draft/diff.expr#4.sentence-3)

**Comment by jensmaurer** [comment]
Updated.

**Comment by zygoloid** [comment]
Looks good, thanks. Did you consider and reject the idea of turning this into a note?

**Comment by jensmaurer** [comment]
@zygoloid: For the overload resolution candidates, I believe the text needs to be normative (the remaining text, taking verbatim, seems to exclude conversion to references).

**Pull request merged**
