### PR TITLE
Comment out ellipses when they mean "more code here" rather than an actual ellipsis token.

### LINKED ISSUE #1390: Comment out ellipses when they mean "more code here" rather than an actual ellipsis token.
Most places already do this, but a few don't:

- [[iostream.forward.overview]/9](http://eel.is/c++draft/iostream.forward.overview#9)
- [[dcl.decl]/3](http://eel.is/c++draft/dcl.decl#3)
- [[expr.prim.lambda]/7](http://eel.is/c++draft/expr.prim.lambda#7)

Interestingly, there are also a couple uses of mega-ellipses consisting of five dots (`.....`):

- [[enumerated.types]/2](http://eel.is/c++draft/enumerated.types#2)
- [[bitmask.types]/2](http://eel.is/c++draft/bitmask.types#2)

But maybe these are fine, because at least `.....` is not the C++ ellipsis token.

### PR DESCRIPTION
**Pull request by Eelis**
Fixes #1390

### CODE REVIEW

**Comment by jwakely** [comment]
Because two of those cases become well-formed code with this change, so it could be argued that the ellipsis implies there's nothing but a comment there :-) What we have today isn't valid C++ and so is obviously meant to indicate something missing from the example. I'm not objecting to the change, but I don't think it's strictly necessary either.

**Comment by Eelis** [comment]
I have no preference beyond consistency :)

**Comment by tkoeppe** [comment]
I agree, the status quo doesn't seem to be bad, broken or confusing.

Regardless, please provide a screenshot.

**Comment by tkoeppe** [comment]
Seems like there's no consensus for change nor anyone violently fighting for this change. I'll close this; please reopen if you feel strongly.

**Pull request closed without merging**
