### PR TITLE
[mdspan.mdspan.overview] Add default template parameters for mdspan

### PR DESCRIPTION
**Pull request by hewillk**
to make it consistent with the declaration.

### CODE REVIEW

**Comment by jensmaurer** [comment]
Repeated default template parameters are ill-formed.

**Comment by hewillk** [comment]
> Repeated default template parameters are ill-formed.

See https://github.com/cplusplus/draft/pull/4836.

**Comment by jwakely** [comment]
Identifiers with _`kebab-case`_ are ill-formed too, but we do that to make things easier to read :slightly_smiling_face: 

Nobody expects to be able to just copy & paste classes from the standard and use them as-is, so we can repeat the defaults if that makes the specification more clear. And I think it does, because often the synopsis is huge and defaults buried there are not obvious.

**Review by jensmaurer — APPROVED** [review]
Ok, looks good.

**Pull request merged**
