### PR TITLE
Introduce term.* labels for [basic.types.general] terms

### LINKED ISSUE #4630: Imprecise cross-references for "trivially copyable type"
[refwrap.general] says:

> `reference_wrapper<T>` is a trivially copyable type (6.8).

Where 6.8 is [basic.types]. The definition of trivially copyable is in 6.8.1 [basic.types.general]. I assume we used to refer to the hanging paragraphs at the start of [basic.types] but they now have their own subclause. The cross-ref should have been updated to refer to that new subclause.

It looks like most cross-references to [basic.types] should actually be [basic.types.general]:

```
$ git grep '{basic.types}' *.tex
atomics.tex:on objects without padding bits\iref{basic.types} is
basic.tex:an incomplete type\iref{basic.types},
basic.tex:in~\ref{basic.types}.
basic.tex:type\iref{basic.types}.
basic.tex:standard-layout type\iref{basic.types} shall occupy contiguous bytes of
basic.tex:zero or more objects of implicit-lifetime types\iref{basic.types}
basic.tex:\ref{basic.types} and the subclauses thereof
basic.tex:Each set of values for any padding bits\iref{basic.types}
basic.tex:the width of that type has padding bits; see \ref{basic.types}.
basic.tex:\keyword{void}\iref{basic.types} has three corresponding cv-qualified
classes.tex:type\iref{basic.types} (or complete type) at the closing \tcode{\}} of
classes.tex:incomplete type\iref{basic.types},
classes.tex:both classes\iref{basic.types}.
classes.tex:types\iref{basic.types}.
classes.tex:\tcode{X} copies the object representation\iref{basic.types} of \tcode{X}.
classes.tex:union \tcode{X} copies the object representation\iref{basic.types} of \tcode{X}.
classes.tex:the extra bits are padding bits\iref{basic.types}.
compatibility.tex:\diffref{basic.types}
concepts.tex:  \item \tcode{T} is a literal type\iref{basic.types},
declarations.tex:is a scalar type\iref{basic.types}, the
declarations.tex:its padding bits\iref{basic.types} are initialized to zero bits and
declarations.tex:its padding bits\iref{basic.types} are initialized to zero bits and
expressions.tex:does not require that type to be complete\iref{basic.types}.
expressions.tex:and~\ref{basic.types} for the definition of object representation.
expressions.tex:thereof~(\ref{intro.object}, \ref{basic.types}, \ref{class.abstract}).
lib-intro.tex:\tcode{T, U, C}    &   any \cv-unqualified object type\iref{basic.types}       \\ \rowsep
lib-intro.tex:If an incomplete type\iref{basic.types} is used as a template
numerics.tex:\tcode{complex<long double>} are literal types\iref{basic.types}.
strings.tex:any non-array trivial standard-layout\iref{basic.types} type.
templates.tex:A template type argument can be an incomplete type\iref{basic.types}.
templates.tex:the instantiation yields an incomplete class type\iref{basic.types}.
templates.tex:classes\iref{basic.types}.
utilities.tex:representation\iref{basic.types} of \tcode{unsigned long long}.
utilities.tex:\tcode{T} is not an incomplete type\iref{basic.types}.
utilities.tex:type\iref{basic.types} that can be the type of the
utilities.tex:\tcode{reference_wrapper<T>} is a trivially copyable type\iref{basic.types}.
utilities.tex:subclause~\ref{basic.types} of the \Cpp{} standard.
utilities.tex:categories, corresponding to the descriptions given in subclause~\ref{basic.types}.
utilities.tex: \tcode{T} is an object type\iref{basic.types}                            &   \\ \rowsep
utilities.tex: \tcode{T} is a scalar type\iref{basic.types}                         &   \\ \rowsep
utilities.tex:is considered to be a trivial~(\ref{basic.types}, \ref{special}) function call
utilities.tex: \tcode{T} is a trivial type\iref{basic.types}     &
utilities.tex: \tcode{T} is a trivially copyable type\iref{basic.types} &
utilities.tex: \tcode{T} is a standard-layout type\iref{basic.types}   &
utilities.tex:  no operation that is not trivial~(\ref{basic.types}, \ref{special}). &
utilities.tex: ~(\ref{basic.types}, \ref{special}). &
utilities.tex: \tcode{T} and \tcode{U} are layout-compatible\iref{basic.types}    &
utilities.tex:is considered to be a trivial~(\ref{basic.types}, \ref{special}) function call
utilities.tex: is no greater than \tcode{Len}\iref{basic.types}.
```

### PR DESCRIPTION
**Pull request by jensmaurer**
For ease of review, these are all separate commits.
Feel free to squash on merge.

Fixes #4630

### CODE REVIEW

**Review by JohelEGP — COMMENTED** [review]
https://github.com/cplusplus/draft/wiki/Specification-Style-Guidelines says "create a \label{term.this.name} at the start of the paragraph defining the term". Perhaps it should say "sentence" rather than "paragraph".

61245eb starts with `[std}` rather than `[std]`.

**Comment by jensmaurer** [comment]
@JohelEGP , fixed both issues.

**Comment by tkoeppe** [comment]
@zygoloid, @opensdh: this looks very nice, but I'd welcome some more Core eyes on those new terms.

**Comment by JohelEGP** [comment]
No new terms were introduced.

**Comment by tkoeppe** [comment]
(I mean the internal labelling of terms. The labelling is new, I suppose, not the terms.)

**Comment by jensmaurer** [comment]
In order to make `\tref` workable, we need LaTeX foo to replace the periods with spaces (or the other way round).

**Comment by tkoeppe** [comment]
(Tangent: if we had a text replacement system for LaTeX, I would also have a nice improvement for the unicode-smallcaps formatting -- I would like to format numerals and letters differently, but I don't know how to do that as a macro.)

**Comment by tkoeppe** [comment]
Why can't `\tref{foo.type}` work like `savebox` where it stored the actual content somewhere else?

**Comment by jensmaurer** [comment]
I guess there are sufficiently many \saveboxes; I thought that's a quite finite resource.
Anyway, the definition of the term would need to translate space to period, which is approximately the same problem.

**Comment by tkoeppe** [comment]
We could use a custom label to store terms. For example:

```
\documentclass[a4paper,11pt]{article}

\makeatletter
\newcommand{\termdef}[2]{%
\protected@write \@auxout {}{\string \newlabel {#1}{{#2}{}}}#2}
\makeatother

\begin{document}
The \ref{term.dcl.spec} shall not be empty.
A \termdef{term.dcl.spec}{decl-specifier} is a thing you can use.
\end{document}
```

**Comment by jensmaurer** [comment]
@tkoeppe, that's not substantially different from my `\label{term...}` approach, which requires less internal knowledge about the structure of the .aux files.

We'd reap real benefits if we could make `\defn` (etc) auto-generate a label that could then be used via `\termref` or similar, giving human-readable space-separated terms in both cases, and internally mapping to a dotted form with a "term." prefix.

Ah, looks like the `xstring` package does exactly that: https://tex.stackexchange.com/questions/36266/replacing-characters-in-argument-strings

**Comment by tkoeppe** [comment]
@jensmaurer, sort of, but what I'm proposing is to just explicitly spell out _both_ the label and the actual term, rather than deriving one from the other. Not only does that require less implementation magic, but it also makes it possible to change the term without changing the label, etc. And the auxfile labelling mechanism is pretty well-established and tractable.

We could make a new command to replace `\ref`, e.g. `\termref`, to make the use clearer at the callsite.

**Comment by jensmaurer** [comment]
@tkoeppe , thanks for your thoughts. See #5210 for an approach that introduces term.* labels automatically.

Note that for each `\defn` (i.e. each term definition), we produce three things:
- text to be shown in the document
- an index entry
- (new) a label

We need macros so that the common case is easy, but (if need be) all three items must be influenceable independently.
For now, #5210 auto-generates labels from (the indexing portion of) \defn, \defnx, \defnadj, \defnadjx, but for index entries using special characters such as ! or @ to fine-tune the indexing, the resulting term.* label is ugly.
That doesn't prevent us from introducing a nice-looking term.* label in the vicinity, though.

In my view, \termref should show both the term and the cross-reference to where it is defined, e.g. "odr-use (6.2)", while naming the term only once.

And just to point out: Memoir creates .aux entries like this for \label:

`\newlabel{term.piecewise.construction}{{\M@TitleReference {20.4.2}{Class template \texttt  {pair}}}{579}{Class template \tcode {pair}}{lstlisting.20.-1376}{}}`

**Comment by jensmaurer** [comment]
Automating the term.* definitions does detect duplicate term definitions quite nicely; see #5210

**Pull request merged**
