### PR TITLE
[dcl.fct] Fix obsolete phrasing when defining 'function type'

### PR DESCRIPTION
**Pull request by jensmaurer**
Fixes cplusplus/CWG#588

### CODE REVIEW

**Comment by jensmaurer** [comment]
@tkoeppe, this feels like an editorial adjustment of outdated wording, from a time when we had two paragraphs talking about function types.  Now, we only have one.

**Comment by jensmaurer** [comment]
@t3nsor , please have a look (no, it's not perfect, but should fix the first-level concern).

**Comment by t3nsor** [comment]
Yeah, it's fine, I guess. It would be nice if the definition could also be moved above

"The declared return type \tcode{U} of the function type is determined as follows:"

but that would require some more extensive rephrasing and it may not be worth the effort.

**Comment by tkoeppe** [comment]
Yes, indeed, the status quo looks off.

**Pull request merged**
