### PR TITLE
[range.join.with.iterator] Add missing 'template' keyword prior to dependent template name 'emplace'

### PR DESCRIPTION
**Pull request by hewillk**

### CODE REVIEW

**Comment by jensmaurer** [comment]
@jwakely, this looks reasonable (although it clutters the presentation).

**Comment by hewillk** [comment]
Note that the `emplace()` in `concat_view`'s specification has the `template` keyword, so this PR should help with consistency.

**Comment by jensmaurer** [comment]
We still need a rebase + force-push.

**Comment by hewillk** [comment]
Because I always submit PRs on the git web page, I haven't actually used git locally for a long long time, so I need to recall these steps. (I've never squash or rebase PRs because I'm not familiar with it, sorry about that. I mostly use p4 system.)

**Comment by jensmaurer** [comment]
"This branch has conflicts that must be resolved"

**Comment by hewillk** [comment]
> "This branch has conflicts that must be resolved"

Thanks for the pointers. 
Now I think these conflicts should be resolved. The current question is how do I merge those disorganized 13 commits into 1 commit _online_?

**Review by jensmaurer — APPROVED** [review]

**Comment by jensmaurer** [comment]
@jwakely, could you please have a look?

Also, this MUST be squashed when merging. The commit history is ... frightening.

**Comment by jwakely** [comment]
```
git checkout -b pr/5455 origin/main
git fetch origin refs/pull/5455/head
git merge --squash FETCH_HEAD
git commit
git push --force-with-lease origin refs/pull/5455/head
```

**Comment by jwakely** [comment]
Hmm, except that has spurious unrelated changes. What did you do?!

**Review by jwakely — APPROVED** [review]
Rebased and force pushed to keep just the commit we want.

**Comment by hewillk** [comment]
> Hmm, except that has spurious unrelated changes. What did you do?!

I don't know, I just did something terrible that I can't remember. I may have `rebase` the wrong branches or something, or `reset` something wrong or something. Anyway I'm sorry for the unspeakable clutter.

**Comment by jwakely** [comment]
What I did was:
```
git checkout -b pr/5455 origin/main
git fetch  https://github.com/hewillk/draft main-2
git merge --squash FETCH_HEAD
git checkout HEAD -- lib-intro.tex threads.tex time.tex # drop the unwanted changes
git commit # and remove all the unrelated cruft in the commit message
git push --force git@github.com:hewillk/draft.git  HEAD:main-2
```

**Comment by jwakely** [comment]
It probably would have been easier to just do:
```
git checkout main
git cherry-pick 573319cc006a3082128d240494efdf8eb2f46cd0
```
i.e. just cherry-pick the one good commit from that messy series of 13 commits. Then force-push that to `main-2`

**Pull request merged**
