### PR TITLE
[index] Create first-letter subheadings for the general index.

### PR DESCRIPTION
**Pull request by jensmaurer**

### CODE REVIEW

**Comment by jensmaurer** [comment]
Here's the new style:
idx2

**Comment by jensmaurer** [comment]
This is rather a basis for discussion.

**Comment by jensmaurer** [comment]
And here is a crazy "table of contents" added:
idx

**Comment by jwakely** [comment]
The table of contents is great, I've wanted that for years.

**Comment by jensmaurer** [comment]
Instead of the funny mini-ToC, I've now added the index letters to the left-hand PDF navigation column, as-if they were subsections. This looks substantially nicer. But maybe people want the mini-ToC anyway.

**Pull request merged**
