### PR TITLE
[conv.rank] Avoid hinting that 'bool' be a standard integer type.

### PR DESCRIPTION
**Pull request by jensmaurer**
Partially addresses #3974

### CODE REVIEW

**Review by jwakely — APPROVED** [review]

**Comment by zygoloid** [comment]
I'm not convinced that this reflects the intent. As with #3974 I want CWG oversight before we try to normatively resolve whether "standard integer types" were intended to include all standard integer types or not.

**Comment by tkoeppe** [comment]
@jensmaurer, @zygoloid: should we close this issue, since this is firmly in CWG's territory?

**Comment by jensmaurer** [comment]
I think this should be presented to CWG on the "editorial oversight" track. I've added this issue to https://wiki.edg.com/bin/view/Wg21telecons2021/CoreWorkingGroup

**Comment by jensmaurer** [comment]
Approved by CWG as an editorial fix.

https://wiki.edg.com/bin/view/Wg21telecons2021/IssuesProcessingTeleconference2021-08-24

**Comment by jensmaurer** [comment]
@tkoeppe , any final thoughts before I merge?

**Pull request merged**
