### PR TITLE
Replace NULL with "null pointer value"

### PR DESCRIPTION
**Pull request by tkoeppe**
Fixes issue #52.

Diff:

image

image

### CODE REVIEW

**Comment by zygoloid** [comment]
This is still wrong -- we should say "an argument that is a null pointer value". We don't care how the null pointer value was written in the source code. But maybe fixing that is a lost cause. Thoughts?

**Comment by tkoeppe** [comment]
PTAL, will upload screenshot shortly.

**Comment by tkoeppe** [comment]
New screenshots:

image

image

**Comment by timsong-cpp** [comment]
@zygoloid But neither `NULL` nor `nullptr` is a null pointer value. The *parameter* has a null pointer value because it is initialized by a null-pointer-constant *argument*, but the argument need not be a null pointer value.

**Comment by tkoeppe** [comment]
@timsong-cpp: yeah... I'm not sure. Even the wording "an `mbstate_t*` argument" is odd. It suggests that the argument already has pointer type. Meh, maybe that's good enough.

**Pull request merged**
