### PR TITLE
[diff] Give numbers to changes.

### PR DESCRIPTION
**Pull request by Eelis**
This follows the direction given in #1367.

Example:

a

### CODE REVIEW

**Comment by jensmaurer** [comment]
Well, this is probably as good as we get visually in this otherwise not-really-pleasing annex.

**Comment by zygoloid** [comment]
It seems a bit odd that the section number (which is part of the change description) is before the paragraph number. Putting a paragraph number before the section number might look a bit strange, though. Let's try adding a "*Something:*" before each such section number list, and moving the paragraph numbers before those.

Some possible options for the "Something": "Modified rule", "Affected wording", "See", "Clause or Subclause".

**Comment by jensmaurer** [comment]
I've created #1837 which uses "Affected subclause" and also cleans up a few oddities in section references throughout [diff].

**Comment by tkoeppe** [comment]
We'll probably use #1837 instead.

**Pull request closed without merging**
