### PR TITLE
[filesystems] Change '!predicate' phrasing to 'predicate is false'.

### LINKED ISSUE #1535: [fs] negation style needs to be harmonized with rest of document
The filesystems subclause use the construction ""If `!exists(p)`" repeatedly, which should be rephrased in our usual way as "If `exists(p)` is `false`".

There are similar constructions for other predicate checks. Basically, all exclamation marks should be expunged from that subclause.

### PR DESCRIPTION
**Pull request by jensmaurer**
Fixes #1535.

### CODE REVIEW

**Comment by zygoloid** [comment]
Diffs look good, this is OK to merge if someone has checked that it's not introducing bad linebreaks or similar. (We've had overfull hboxes in this area previously, as I recall.)

**Comment by jensmaurer** [comment]
Current HEAD show one overfull hbox with "fgrep -e Overfull -e .tex std.log":
`Overfull \vbox (4.77557pt too high) has occurred while \output is active []`

This branch, rebased on the HEAD, shows only that very same overfull hbox.

**Comment by tkoeppe** [comment]
@jensmaurer: Your so-called "hbox" has self-identified as a "vbox" and would like you to treat it as such.

**Comment by jensmaurer** [comment]
Dear vbox,

Please accept my sincere apologies for mistreatment as a hbox.

Jens

**Comment by tkoeppe** [comment]
Looks all good, no hboxes were disrespected as part of this pull request.

**Pull request merged**
