### PR TITLE
[containers] Add a space after "Requires:"

### PR DESCRIPTION
**Pull request by jlaire**

### CODE REVIEW

**Comment by tkoeppe** [comment]
Can you please attach a screenshot of the diffpdf?

**Comment by jlaire** [comment]
I will try to do that later today. I just noticed that the spacing looks bad and all other uses of `\requires` inside tables are followed by the escaped space.

**Comment by jwakely** [comment]
Where is the spacing bad? I see no changes from this change (visually, or using diffpdf), so it doesn't seem to have any effect.

**Comment by tkoeppe** [comment]
Indeed, since the macro uses xspace I expect there to not be an effect. I also don't see anything wrong with the status quo.

**Comment by jlaire** [comment]
Darn, I was reading n4606.pdf. It's getting quite old compared to master.

**Comment by tkoeppe** [comment]
@jlaire: the current working paper is n4618.pdf.

**Pull request closed without merging**
