### PR TITLE
[library] Change program-defined to user-defined

### LINKED ISSUE #1090: Meaning of "program-defined"
There are 4 instances of the term "program-defined" in the standard. Does it have the same meaning as "user-defined"?

### PR DESCRIPTION
**Pull request by jlaire**
Fixes #1090.

### CODE REVIEW

**Comment by tkoeppe** [comment]
@jwakely: Could you please review this?

**Comment by timsong-cpp** [comment]
See http://cplusplus.github.io/LWG/lwg-active.html#2139; this P/R seems to be going in the opposite direction.

**Comment by tkoeppe** [comment]
Absolutely, which is why I wanted Jon to comment on this proposal.

**Comment by jlaire** [comment]
Ah, I wasn't aware that. But given that program-defined isn't currently defined and it's used only a few times (compared to over a hundred hits for user-defined), the situation is a bit silly.

**Comment by jwakely** [comment]
This is a step backwards, I'm trying to get the library to stop using that term. Changing from one undefined term to a different undefined term that means two different things in different parts of the standard is not an improvement.

**Pull request closed without merging**
