### PR TITLE
[expr.cond] drop redundant subclause (CWG 2316)

### PR DESCRIPTION
**Pull request by cubbimew**
proposed fix for #1373

### CODE REVIEW

**Comment by jensmaurer** [comment]
These words are quick to anger... For @zygoloid to decide whether this is editorial or needs CWG review.

**Comment by zygoloid** [comment]
I'm confident that the old and new words have the same meaning, but I'd like CWG review to double-check that we don't *intend* for these two cases to be handled differently any more. (As I recall, they did actually do different things before we reformulated this in terms of implicit conversion sequences in CWG1895.)

**Comment by cubbimew** [comment]
resolved a conflict with https://github.com/cplusplus/draft/commit/cf283d86d2fecd1190fa9c437d73da70a35060bd

**Comment by tkoeppe** [comment]
@jensmaurer, @zygoloid: Did this PR ever come up in CWG?

**Comment by cpplearner** [comment]
I suspect that [CWG2316](https://wg21.link/cwg2316) is related, though I can't see the detailed description.

**Comment by tkoeppe** [comment]
@cubbimew Rebase this regardless please if you don't mind, so that CWG can look at current wording.

**Comment by tkoeppe** [comment]
@cubbimew: rebase please?

**Comment by cubbimew** [comment]
rebased

**Comment by jensmaurer** [comment]
Approved by CWG telecon 2020-08-17.

**Comment by hubert-reinterpretcast** [comment]
Not that anyone implemented it that I know of, but this reverts the resolution to CWG 2321 (http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1113r0.html) adopted by the June 2018 Rapperswil meeting.

Compiler Explorer link demonstrating (at this time) non-adoption of the resolution to CWG 2321: https://godbolt.org/z/f8KqaM.

**Comment by opensdh** [comment]
I don't understand, now, how that resolution was necessary anyway: if you fall through to the other bullet in the issue's example, isn't the target type `A`, to which `const B` can be implicitly converted?

**Comment by jensmaurer** [comment]
The change was reverted in 02474121ba0ecde1871a52e409ba5174fb79c89f because it reverts CWG 2321. Such action is not editorial, and furthermore unintended.

**Comment by hubert-reinterpretcast** [comment]
> I don't understand, now, how that resolution was necessary anyway: if you fall through to the other bullet in the issue's example, isn't the target type `A`, to which `const B` can be implicitly converted?

Maybe that's why MSVC accepts but with different cv-qualification for the result than CWG 2321 would give.

**Pull request merged**
