### PR TITLE
[time.syn] Rename to [chrono.syn], consistent with header name

### LINKED ISSUE #1958: rename [time.syn] to [chrono.syn]
We should consistently name the header synopsis for the header <foo> [foo.syn].

### PR DESCRIPTION
**Pull request by jensmaurer**
Fixes #1958.

### CODE REVIEW

**Comment by jensmaurer** [comment]
@W-E-Brown objects to this change; see #1991.

**Comment by jensmaurer** [comment]
@zygoloid, this one is for you; please consider @W-E-Brown's objection in #1991.

**Comment by zygoloid** [comment]
This is controversial, so let's discuss this in person, and make sure Walter is there for that discussion.

**Comment by jensmaurer** [comment]
Closed as per editorial meeting decision, recorded in #1958.

**Pull request closed without merging**
