### PR TITLE
P1413R3 Deprecate std::aligned_storage and std::aligned_union

### LINKED ISSUE #5265: [2022-02 LWG Motion 6] P1413R3 Deprecate std::aligned_storage and std::aligned_union
[P1413R3](https://wg21.link/p1413r3)

### PR DESCRIPTION
**Pull request by jensmaurer**
- Replace 'shall be' with 'is'.

Fixes #5265
Fixes cplusplus/papers#197

### CODE REVIEW

**Comment by tkoeppe** [comment]
@jensmaurer Are the removals of the table rows in tab:meta.trans.other missing? I can add those.

**Comment by tkoeppe** [comment]
Ah, no, but there's a stray note that should probably also have been deleted.

**Comment by jensmaurer** [comment]
Yes, the stray note should go, too.

**Comment by tkoeppe** [comment]
I'm actually going to _move_ it to the Annex, given that we already have another note there.

**Comment by tkoeppe** [comment]
(I'll apply the unrelated is_pod index fix after the motions.)

**Pull request merged**
