### PR TITLE
Make "at least as specialized" an indexed term.

### PR DESCRIPTION
**Pull request by burblebee**

### CODE REVIEW

**Comment by tkoeppe** [comment]
I like the idea of indexing this term, but I'm not sure if the passage you chose constitutes a *definition* of this term. As far as I understand it, this is only one of the constituent definitions.

**Comment by tkoeppe** [comment]
@burblebee: do you have any further thoughts on this? Is the problem real and warrants a PR?

**Comment by tkoeppe** [comment]
@burblebee: Ping :-)

**Comment by burblebee** [comment]
I agree - I should restrict this occurrence of the term to template parameters, and add another index for the templates themselves.  Sound good?

**Comment by tkoeppe** [comment]
We already have one entry for "at least as specialized", but it redirects to "more specialized". I suppose we shouldn't be redirecting to two distinct places?

**Comment by burblebee** [comment]
@tkoeppe: What do you propose we do?

**Comment by tkoeppe** [comment]
I'm not sure. Is "more specialized" also a sensible top-level index entry? If so, maybe we can have multiple index entries for the various parts of this section that are all grouped under "more specialized"?

@zygoloid, any opinions?

@AlisdairM: Dawn has been trying to add an index entry for "at least as specialized"; aren't you the resident indexing expert?

**Comment by burblebee** [comment]
We agreed that my resolution was insufficient - closing this pull request.

**Pull request closed without merging**
