### PR TITLE
[range.cartesian.view] Remove unused template parameter

### PR DESCRIPTION
**Pull request by hewillk**
Is it reasonable to do so?

### CODE REVIEW

**Comment by JohelEGP** [comment]
Part of #5735. I don't see why not.

**Comment by CaseyCarter** [comment]
I think I'd rather see the unused template parameter pack removed from the exposition-only concept; there are only four uses to clean up.

**Comment by hewillk** [comment]
> I think I'd rather see the unused template parameter pack removed from the exposition-only concept; there are only four uses to clean up.

https://github.com/cplusplus/draft/issues/5735#issuecomment-1222560612: "is a cartesian product of all of these ranges a common range?". That's also why it takes all the ranges as arguments, instead of just the first one.

Although it's clearly the intended design. I think it's more straightforward to just remove the template parameter pack, and I don't see how it would cause confusion, so I prefer removing it.

**Comment by tkoeppe** [comment]
@CaseyCarter Would that be editorial, or should we open an LWG issue to remove the pack?

**Review by CaseyCarter — APPROVED** [review]

**Comment by CaseyCarter** [comment]
> @CaseyCarter Would that be editorial, or should we open an LWG issue to remove the pack?

I think the change in the PR is both clearly editorial, and a minor readability improvement. Nothing says "yes, I really intend to ignore this parameter" as explicitly as does leaving it unnamed.

Any further simplifications - Should we remove the parameter pack? Should we replace uses of `cartesian-product-is-common<T, Us...>` with `cartesian-product-common-arg<T>` and remove the former altogether? - probably ought to go through LWG. The current structure was put in place for readability, and while we may not all agree that it's ideal, we should give plenty of eyes the chance to comment on any larger structural change.

**Comment by tkoeppe** [comment]
@CaseyCarter Thanks!

@hewillk Please file an LWG issue if you want to remove the template parameter.

**Pull request merged**
