### PR TITLE
[enumerated.types,bitmask.types] Use \vdots and \ldots instead of ...…

### PR DESCRIPTION
**Pull request by jensmaurer**
….. mega-ellipses.

Partially addresses #1390.

### CODE REVIEW

**Comment by tkoeppe** [comment]
@zygoloid, @jensmaurer: I think we really want AmsMath's \dotsc behaviour for comma-separated lists, not blanket \cdots, and the guidance in #1390 should be adjusted accordingly.

**Comment by jensmaurer** [comment]
@zygoloid said in #1390 that we wanted "center dots", but in this case, \ldots look substantially better. I've updated the pull request to use \ldots, so this can be applied right away once @zygoloid has changed his opinion.
@tkoeppe: We use both \ldots (45 appearances) and \dotsc (33 appearances). We should decide on one form. I've created #2032 to follow up on this.

**Comment by tkoeppe** [comment]
@jensmaurer: they might not quite the same, though. \ldots is kind of generic, "presentational" form. \dotsc is specifically for use in math mode, I think: $x_0, x_1, \dotsc, x_n$. We should look more carefully at how \ldots and \dotsc are currently used; the status quo may already be WAI.

**Comment by jensmaurer** [comment]
The predominant usage of \ldots in our standard is within math mode with comma-separated lists of things. The same statement applies to \dotsc.
As a first step, we should probably move towards \dotsc for comma-separated lists of things and see what remains.
@zygoloid?

**Comment by zygoloid** [comment]
Let's move the discussion to #1390. This looks good to merge as-is, as a start down this road.

**Pull request merged**
