### PR TITLE
No indefinite articles before grammatical productions

### PR DESCRIPTION
**Pull request by 18**
Pretty simple grammatical fix

### CODE REVIEW

**Comment by tkoeppe** [comment]
I don't think the status quo is wrong here. "A form of if statement" seems like a correct way to refer to the different forms.

**Comment by 18** [comment]
I feel that an article here is needed, since we are referring to a construct, and it reads a lot smoother, 

However, if the consensus if that its fine, then we should make the use consistent.

**Comment by jensmaurer** [comment]
It seems to me the status quo is fine here. "In the first form of mutiny, all participants are incarcerated. In the second form of mutiny, all participants are beheaded." sounds reasonable.

**Comment by 18** [comment]
@jensmaurer Alright. Should we atleast make the use consistent? For example, http://eel.is/c++draft/dcl.dcl#dcl.init-16.5 uses an indefinite article before the noun, but http://eel.is/c++draft/dcl.dcl#dcl.init-1.sentence-2 doesn't.

**Comment by jensmaurer** [comment]
So, this turned into a consistency question, and the suggested pull request here actually does not address the consistency issue to the extend we know about it.

**Comment by 18** [comment]
@jensmaurer I'll change the PR accordingly.

**Comment by zygoloid** [comment]
"the second form of `if` statement" is talking about the general category of `if` statements, which have multiple forms, so omitting the indefinite article there seems correct (we're not talking about a single `if` statement that has multiple forms, so "an" is inappropriate). The cases affected by the revised pull request are talking about a specific instance of a grammar production, and for those cases, the indefinite article is appropriate.

I don't think there's a systematic problem here, and I'm unconvinced that any of the changes so far are improvements.

**Pull request closed without merging**
