### PR TITLE
[over.best.ics] Fix a typo in "user-defined conversion sequence" (fixes #535)

### LINKED ISSUE #535: Wrong term used in [over.best.ics]/10
> […] or the purpose of ranking implicit conversion sequences as described in 13.3.3.2, the ambiguous conversion sequence is treated as a **user-defined sequence** that is indistinguishable from any other user-defined conversion sequence<sup>134</sup>.

That's probably meant to read "user-defined conversion sequence".

### PR DESCRIPTION
**Pull request by Arcoth**

### CODE REVIEW

**Comment by tkoeppe** [comment]
Can you please change the commit message to the canonical format (starting with the stable section name and summarizing the actual change)?

**Comment by tkoeppe** [comment]
@Arcoth: Ping

**Comment by Arcoth** [comment]
@tkoeppe Oh, sorry. Will fix shortly.

**Comment by tkoeppe** [comment]
@zygoloid: PTAL?

**Pull request merged**
