### PR TITLE
[concept.swappable] remove wrongly included text

### PR DESCRIPTION
**Pull request by timsong-cpp**
These paragraphs are in magenta in P0898R3 and are not meant to be included into the IS working draft.

### CODE REVIEW

**Comment by CaseyCarter** [comment]
@timsong-cpp is right: this is my mistake.

**Comment by tkoeppe** [comment]
Ah, that's because plain "magenta" isn't a thing: P0893R3 only defines "mangeta with strikethrough". So I suppose that's an error in the original paper already that translated into erroneous application?

**Comment by CaseyCarter** [comment]
> Ah, that's because plain "magenta" isn't a thing: P0893R3 only defines "mangeta with strikethrough".

The magenta comes from the `\oldtxt` macro, which is basically `\removed` with a different color. It can't be applied to markup, and large blocks of strikethrough do nothing for clarity, so I usually just `{\color{oldclr} ...}` large blocks. The error in the paper is not describing the usage of "red/magenta without strikethrough" and "cyan/gold without underline" correctly.

Also, "Mangeta" sounds like one of Godzilla's opponents - or a Super Sayan.

**Comment by tkoeppe** [comment]
"Mangeta" is clearly the spin-off following the adventures of Magneta's manservant.

_Attractive._ &mdash; Critics.

**Pull request merged**
