### PR TITLE
[index] Add index of concept names.

### LINKED ISSUE #2959: An index of library concepts would be extremely useful
The standard library specification is filling up with concepts, especially "exposition only" concepts, and Cpp17Requirements.  It is often necessary to locate the definition of these concepts to understand the clause you are reading, and there is no easy collected reference to find them.  We could look into the index of library names, but it is not clear that the exposition-only names belong there.

It would be helpful to add a new index for all library concepts, including the exposition-only ones denoted by appearing in italics.  It might also be useful to index the Cpp17Requirements, but most of those are reasonably easy to find today, and with a consistent prefix naming convention, perhaps better served by consistently adding them to the main index (where some, but not all, already reside).

### PR DESCRIPTION
**Pull request by jensmaurer**
Fixes #2959.

### CODE REVIEW

**Comment by tkoeppe** [comment]
I haven't looked at the output, but as long as it works with `latexmk` and looks as expected, the approach looks reasonable. Feel free to merge!

**Comment by jensmaurer** [comment]
Sample index page:

index

Since this is replacing \placeholder/nc with semantic macros (without the "nc"), there are some slight whitespace changes in the main text.

Before:
before2

After:
after2

If this is undesirable, I fear I have to introduce "nc" variants of the macros. Please advise.

**Comment by jensmaurer** [comment]
(Uh, same-as shouldn't be italics in the "after" picture. Will fix right now.)

**Comment by jensmaurer** [comment]
Editorial teleconference: introduce \libconceptx to fix \cname use in ranges.tex. Otherwise good to merge.

**Comment by jwakely** [comment]
This seems to have borked the bookmarks in the PDF:
Screenshot_20191010_102740

**Comment by jensmaurer** [comment]
Rats.

**Comment by jensmaurer** [comment]
Is there any way to do different things in an \rSec vs. outside?

**Comment by jensmaurer** [comment]
Repaired by #3286.

**Comment by Eelis** [comment]
For the `same_as` example, the concept index now also has an entry for _`same-as-impl`_, which is an exposition-only name only used in the implementation of `same_as`.
Was this intentional? :) Looks a bit weird, because why would a reader ever look up _`same-as-impl`_ in the index?

**Comment by jensmaurer** [comment]
Well, in general we also add exposition-only concepts to the index, because they might be used far away from their definition. That's certainly not the case for same-as-impl, but it feels slightly inconsistent to decide this on a case-by-case basis.

**Comment by Eelis** [comment]
Ah fair enough, thanks!

**Pull request merged**
