### PR TITLE
[std] Replace hyphen with period in labels

### LINKED ISSUE #5225: inconsistent use of periods versus hyphens in [defns]
In some labels in defns, hyphens in a term translate into hyphens in the label:
* [defns.direct-non-list-init]
* [defns.expression-equivalent]

In other labels, they become periods:
* [defns.prog.def.spec]
* [defns.prog.def.type]

Finally we have some cases where the noun is dropped when abbreviating to form the label; in these cases we seem to consistently use a period rather than a hyphen:
* [defns.cond.supp]
* [defns.impl.defined]
* [defns.locale.specific]
* [defns.well.formed]

(That last category might make sense, because English style guides often say to omit the hyphens in compound adjectives when used without a noun, but we don't do that in the standard, eg: "the behavior is implementation-defined" not "the behavior is implementation defined".)

Some consistency here would be nice. Maybe the first two examples above should change from hyphens to periods?

### PR DESCRIPTION
**Pull request by jensmaurer**
and add a check.

Fixes #5225

### CODE REVIEW

**Comment by jensmaurer** [comment]
@zygoloid, at your service.

**Review by zygoloid — APPROVED** [review]
Thanks, I like it.

@tkoeppe How do you feel about requiring labels to match `/[0-9a-z.]*/`?

**Comment by tkoeppe** [comment]
Are you referring to (visible) stable labels or to the internal term labels?

**Comment by jensmaurer** [comment]
@tkoeppe, this issue is dealing with (visible) stable section labels, only. So, the question is: Are fine with hard-limiting (visible) stable section to match /[0-9a-z.]*/

**Comment by tkoeppe** [comment]
I'm not fully convinced byt the resulting restrictions, since this forces us to conflate mere compound words with the hierarchical use of dots, e.g. `foo.bar`, `foo.bar.general` (subsection) would have to contend with `foo.bar.tender` (sibling section).

Practically, though, a) this particular change is very small and I have no issue with the handful of labels touched here, and b) we (or at least Jens's script) already seem to be claiming that the existing use of hyphens is "bad", so it seems like we already made that decision.

So consider this a non-enthusiastic approval.

**Comment by jensmaurer** [comment]
This needs a rebase, though.

**Pull request merged**
