### PR TITLE
8.1.5.4 Add capture to the j variant to make the example to be compiled

### PR DESCRIPTION
**Pull request by anatoly-spb**
Here is  a small fix to make the 8.1.5.4 example to be compiled.

### CODE REVIEW

**Comment by cpplearner** [comment]
See #609

**Comment by tkoeppe** [comment]
@cpplearner: Thanks for the reference.

Closing, since there is nothing wrong with the example.

**Comment by berkus** [comment]
Since you got two reports on this where people think the capture is erroneously missing - it makes sense to add a comment to this snippet explaining the expected `j` scope.

**Comment by tkoeppe** [comment]
The standard is not a tutorial?

@zygoloid: what do you think?

**Comment by timsong-cpp** [comment]
[expr.prim.lambda]'s examples are all over the place w/r/t scope. Many are scope-neutral, so to speak, but we do have stuff like [this](https://timsong-cpp.github.io/cppwp/expr#prim.lambda.capture-13.example-1) that only works at block scope, stuff like the one at issue here that only works at namespace scope, and then stuff like [this](https://timsong-cpp.github.io/cppwp/expr#prim.lambda.closure-7.example-1) that actually needs to be split up and put into two different scopes to compile. Meanwhile, we also have examples like [this](https://timsong-cpp.github.io/cppwp/expr#prim.lambda.capture-5.example-1) that introduces a function solely to get a block scope so that captures can be used. It might not be a bad idea to come up with some rule on scopes for examples and apply it uniformly.

In this particular case, I would argue that the example could use some improvement; there's no explicit marker that the declarations are at namespace scope, and I'd wager that local lambdas arise more frequently than global ones, so the "missing capture" gets distracting because it resembles a common programming error with local lambdas. But I dislike an explicit comment too, as that also distracts from the point of the example, which has nothing to do with scope or captures. 

How about just adding a `static` before `int j;`?

**Pull request closed without merging**
